// reactapp-uadmin/src/components/Course_Edit/Course_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import DepartmentService from "../../services/department.service";
import AssignmentService from "../../services/assignment.service";
import CourseService from "../../services/course.service";

import { useNavigate } from "react-router";

import Moment from "moment";

const Course_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();
  const [faculties, setFaculties] = useState([]);

  const [modelErrors, setModelErrors] = useState([]);
  const [courseEditResponse, setCourseEditResponse] = useState({});

  // form
  const [courseName, setCourseName] = useState("");
  const [facultyId, setFacultyId] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      getCourse(id);
    }
  }, []);

  const getCourse = (id) => {
    console.log("Editing course : ", id);
    if (checkForNumbersOnly(id)) {
      CourseService.getCourse(id)
        .then((response) => {
          if (response.data === "") {
            // data not found on server!
            var courseEditResponse = {
              responseCode: -1,
              responseMessage: "Course Not Found!",
            };

            setCourseEditResponse(courseEditResponse);
          } else {
            console.log(response.data);

            setCourseName(response.data.courseName);
            setFacultyId(response.data.currentFacultyId);
            setDepartmentId(response.data.departmentId);
            setFaculties(response.data.facultyList);
          }
        })
        .catch((e) => {
          console.log(e);
        });
    } else navigate("/course");
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const handleCourseName = (event) => {
    setCourseName(event.target.value);
    if (!errors[courseName])
      setErrors({
        ...errors,
        courseName: "",
      });
  };
  const handleFacultyId = (event) => {
    setFacultyId(event.target.value);
    if (!errors[facultyId])
      setErrors({
        ...errors,
        facultyId: "",
      });
  };
  const handleDepartmentId = (event) => {
    setDepartmentId(event.target.value);
    if (!errors[departmentId])
      setErrors({
        ...errors,
        departmentId: "",
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const newErrors = {};

    if (!courseName || courseName === "")
      newErrors.courseName = "Course Name is Required!";

    if (!facultyId || facultyId === "")
      newErrors.facultyId = "Faculty is Required!";
    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var courseModel = {
        couseName: courseName,
        departmentId: Number(departmentId),
        facultyId: Number(facultyId),
        couseId: Number(id),
      };

      console.log(courseModel);
      // api call
      CourseService.editCourse(courseModel)
        .then((response) => {
          console.log(response.data);
          setModelErrors([]);
          setCourseEditResponse({});
          var courseEditResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          resetForm();
          setCourseEditResponse(courseEditResponse);
          if (response.data.responseCode === 0) {
            setTimeout(() => {
              navigate("/course");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setCourseEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          } else {
            console.log(error);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setCourseName("");
    setDepartmentId("");
    setFacultyId("");
    setCourseEditResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  const renderOptionsForFaculties = () => {
    return faculties.map((dt, i) => {
      return (
        <option value={dt.facultyId} key={i} name={dt.facultyName}>
          {dt.facultyName}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-8 mx-auto">
            <div className="card">
              <div className="card-header header">
                <h3>Edit Course # {id}</h3>
                <p></p>{" "}
                {courseEditResponse &&
                courseEditResponse.responseCode === -1 ? (
                  <span className="courseEditError">
                    {courseEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="courseEditSuccess">
                    {courseEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-5 mx-auto">
                      <Form.Group controlId="courseName">
                        <Form.Label>Course Name</Form.Label>
                        <Form.Control
                          value={courseName}
                          type="text"
                          isInvalid={!!errors.courseName}
                          onChange={(e) => handleCourseName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.courseName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="facultyId">
                        <Form.Label>Faculty</Form.Label>
                        <Form.Control
                          as="select"
                          value={facultyId}
                          isInvalid={!!errors.facultyId}
                          onChange={(e) => handleFacultyId(e)}
                        >
                          <option value="">Select Faculty</option>
                          {renderOptionsForFaculties()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.facultyId}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Faculty
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Course_Edit;

// ngApp/src/app/course-edit/course-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import Department from '../models/department';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import Faculty from '../models/faculty';
import Course from '../models/course';
import FacultyList from '../models/facultyList';

@Component({
  selector: 'app-course-edit',
  templateUrl: './course-edit.component.html',
  styleUrls: ['./course-edit.component.css']
})
export class CourseEditComponent implements OnInit {

  // ui can change facultyId for a particular courseId @Course db table
  // so run code @Assignment db table to change facultyId column value for
  // a respective courseId
  // set FacultyId = new value
  // where CourseId = courseId of currently changed course's courseId
  // ui can change faculty value only belong to same department where 
  // currently course is having department value

  // can't change
  couseId: string;
  departmentId: number;
  departmentName: string;
 
  // can change
  facultyId: number;
  departments: Array<Department>;
  faculties: Array<FacultyList>;

  crsForm: FormGroup;
  submitted = false;
  courseModel = new Course();

  editCrsPanel = true;

  apiResponse = '';
  responseColor = '';

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
   this.crsForm = this.fb.group({
     CourseName: ['', Validators.required],
     FacultyId: ['', Validators.required]
   });

   this.couseId = this.route.snapshot.paramMap.get('id');
   if (this.couseId == '') {
     return;
   }
   else {
     // do api call to retrieve latest course information
     this.dataService.getCourse(Number(this.couseId))
       .subscribe(
         data => {
           if (data == null) {
              console.log('course not found!');
              this.editCrsPanel = false;
              // fail
              // display error message
              this.apiResponse = 'Course Not Found!';
              this.responseColor = 'red';
           }
           else {
             this.apiResponse = '';
             this.responseColor = 'green';
             this.editCrsPanel = true;

              // popup form data with incoming api data call  
              this.crsForm.setValue({
                CourseName: data.courseName,
                FacultyId: data.currentFacultyId
              });
              this.faculties = data.facultyList;
              this.departmentId = data.departmentId;
              this.departmentName = data.departmentName;
           }
         },
         error => {
           console.log('course not found!');
           this.editCrsPanel = false;
           // fail
           // display error message
           this.apiResponse = 'Course Not Found!';
           this.responseColor = 'red';
         });
   }
 }
  
  // ok  
  get crsFormControl() {
    return this.crsForm.controls;
  }

  onSubmit(): void {
    this.submitted = true;
    if (this.crsForm.valid) {
      this.courseModel.couseName = this.crsForm.value["CourseName"];
      this.courseModel.departmentId = this.departmentId;
      this.courseModel.facultyId = Number(this.crsForm.value["FacultyId"]);
      this.courseModel.couseId = Number(this.couseId);

      this.dataService.editCrs(this.courseModel)
        .subscribe(
          response => {
            if (response.responseCode == 0) {
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.editCrsPanel = false;

              // redirect to course component
              setTimeout(() => {
                this.router.navigate(['/course']);
              }, 3000);
            }
            else {
              // fail
              // display error message
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
              this.editCrsPanel = true;
            }
          },
          error => {
            this.apiResponse = error;
            this.responseColor = 'red';
            this.editCrsPanel = true;
          }
        );
    }
  }

  resetCrs() {
    this.apiResponse = '';
    this.responseColor = '';
    this.crsForm.reset();
    this.submitted = false;

    this.router.navigate(['/course']);
  }

}

<div class="container">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-header">
                <h3>
                    <div>
                        #{{couseId}}) Course - Edit
                    </div>
                    <hr />
                    <h4 *ngIf="apiResponse">
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                        <hr />
                    </h4>
                </h3>
            </div>
            <div class="card-body" 
                *ngIf="editCrsPanel">
                <form class="form-crs" 
                    [formGroup]="crsForm" 
                    (ngSubmit)="onSubmit()">
                    <div class="form-group">
                        <label>Course Name</label>
                        <input type="text" 
                            class="form-control" 
                            formControlName="CourseName">
                        <span class="text-danger"
                            *ngIf="(crsFormControl.CourseName.touched || submitted) && crsFormControl.CourseName.errors?.required">
                            Course Name is required
                        </span>
                    </div>
                    <!-- faculty list -->
                    <div class="form-group">
                        <label>Faculty : </label>
                        <select class="form-control" 
                            formControlName="FacultyId">
                            <option value="">Choose Faculty</option>
                            <option value={{f.facultyId}}
                                 *ngFor="let f of faculties">
                                {{f.facultyName}}
                            </option>
                        </select>
                        <div *ngIf="submitted && crsFormControl.FacultyId.errors?.required" 
                            class="alert alert-danger mt-2">
                            Please choose Faculty
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-3">
                                <button type="submit" 
                                    class="btn btn-success">
                                    Edit
                                </button>
                            </div>
                            <div class="col-sm-6">
                                <button type="button" 
                                    (click)="resetCrs()" 
                                    class="btn btn-primary">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
