// reactapp-uadmin/src/components/Department_Edit/Department_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import DepartmentService from "../../services/department.service";

import { useNavigate } from "react-router";

import Moment from "moment";

const Department_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();

  const [modelErrors, setModelErrors] = useState([]);

  const [deptEditResponse, setDeptEditResponse] = useState({});

  // form
  const [departmentName, setDepartmentName] = useState("");
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else getDepartment(id);
  }, []);

  const getDepartment = (id) => {
    console.log("Editing department : ", id);
    if (checkForNumbersOnly(id)) {
      DepartmentService.getDepartment(id)
        .then((response) => {
          if (response.data === "") {
            // data not found on server!
            var deptEditResponse = {
              responseCode: -1,
              responseMessage: "Department Not Found!",
            };

            setDeptEditResponse(deptEditResponse);
          } else {
            console.log(response.data);

            setDepartmentName(response.data.departmentName);
          }
        })
        .catch((e) => {
          console.log(e);
        });
    } else navigate("/department");
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const handleDepartmentName = (event) => {
    setDepartmentName(event.target.value);
    if (!errors[departmentName])
      setErrors({
        ...errors,
        departmentName: "",
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const newErrors = {};

    if (!departmentName || departmentName === "")
      newErrors.departmentName = "Department Name is Required!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var deptModel = {
        // check for ModelState @api
        departmentName: departmentName,
        // departmentName: null,
        departmentId: parseInt(id),
      };

      console.log(deptModel);

      // api call
      DepartmentService.editDepartment(deptModel)
        .then((response) => {
          console.log(response.data);
          setModelErrors([]);
          setDeptEditResponse({});
          var deptEditResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          resetForm();
          setDeptEditResponse(deptEditResponse);
          if (response.data.responseCode === 0) {
            setTimeout(() => {
              navigate("/department");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setDeptEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          } else {
            console.log(error);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setDepartmentName("");
    setDeptEditResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-6 mx-auto">
            <div className="card">
              <div className="card-header header">
                <h3>Edit Department # {id}</h3>
                <p></p>{" "}
                {deptEditResponse && deptEditResponse.responseCode === -1 ? (
                  <span className="deptEditError">
                    {deptEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="deptEditSuccess">
                    {deptEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-6 mx-auto">
                      <Form.Group controlId="departmentName">
                        <Form.Label>Department Name</Form.Label>
                        <Form.Control
                          value={departmentName}
                          type="text"
                          isInvalid={!!errors.departmentName}
                          onChange={(e) => handleDepartmentName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.departmentName}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Department
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Department_Edit;

// NgApp/src/app/department-edit/department-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import Department from '../models/department';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-department-edit',
  templateUrl: './department-edit.component.html',
  styleUrls: ['./department-edit.component.css']
})
export class DepartmentEditComponent implements OnInit {

  // can't change
  // only departmentname can be edited
  departmentId: string;

  deptForm: FormGroup;
  submitted = false;
  departmentModel = new Department();

  editDeptPanel = true;

  apiResponse = '';
  responseColor = '';
  errors: string[];

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute)
  { }

  // ok
  ngOnInit(): void {
    this.deptForm = this.fb.group({
      DepartmentName: ['', Validators.required]
    })

    
    this.departmentId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.departmentId)) {
      console.log('Not a Number!');
      this.router.navigate(['/department']);
    }
    else {
      // do api call to retrieve latest department information 
      this.dataService.getDepartment(Number(this.departmentId))
        .subscribe(
          data => {
            if(data==null){
              console.log('department not found!');
              this.editDeptPanel = false;
              // fail
              // display error message
              this.apiResponse = 'Department Not Found!';
              this.responseColor = 'red';
            }
            else{
              this.apiResponse = '';
              this.responseColor = 'green';
              this.editDeptPanel = true;

              console.log(data);
              // popup form data with incoming api data call          
              this.deptForm.setValue({
                DepartmentName: data.departmentName
              });
            }
          },
          error => {
            console.log(error);
          });
    }
  }

  // ok
  get deptFormControl() {
    return this.deptForm.controls;
  }

  // ok
  onSubmit(): void {
    this.responseColor = '';
    this.errors = [];    
    this.apiResponse = '';

    this.submitted = true;
    if (this.deptForm.valid) {
      this.departmentModel.departmentName = this.deptForm.value["DepartmentName"];
      // this.departmentModel.departmentName = null;
      this.departmentModel.departmentId = Number(this.departmentId);

      this.dataService.editDept(this.departmentModel)
        .subscribe(
          response => {
            // 0
            if (response.responseCode === 0) {
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.editDeptPanel = false;  
              
              // redirect to department component
              setTimeout(() => {
                this.router.navigate(['/department']);
              }, 3000);
            }
            // -1
            else {
              // fail
              // display error message
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
              this.editDeptPanel = true;
            }
          },
          error => {
            this.apiResponse = '';
            this.responseColor = 'red';
            this.editDeptPanel = true;
            // 400
            // ModelState @api
            if (error.status === 400) {   
              this.errors = this.localDataService.display400andEx(error, 'Registration');      
            }
            else {
              console.log(error);
            }
          }
        );
    }
  }

  // ok
  resetDept(){
    this.apiResponse = '';
    this.responseColor = '';
    this.errors = [];  
    this.deptForm.reset();
    this.submitted = false;

    this.router.navigate(['/department']);
  }
}

<div class="container">
    <div class="col-md-5 mx-auto">
        <div class="card" 
            style="background-color:  lightgoldenrodyellow;">
            <div class="card-header">
                <h3>
                    <div>
                        #{{departmentId}}) Department - Edit
                    </div>
                    <hr />
                    <h5 *ngIf="apiResponse">
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                        <hr />
                    </h5>
                    <h5 *ngIf="errors?.length > 0">
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of errors">
                                {{ error }}
                            </li>
                        </ul>
                    </h5>
                </h3>
            </div>
            <div class="card-body" *ngIf="editDeptPanel">
                <form class="form-dept" 
                    [formGroup]="deptForm" 
                    (ngSubmit)="onSubmit()">
                    <div class="form-group">
                        <label>Department Name</label>
                        <p></p>
                        <input type="text" 
                            class="form-control" 
                            formControlName="DepartmentName">
                            <p></p>
                        <div class="alert alert-danger mt-2"
                            *ngIf="(deptFormControl.DepartmentName.touched || submitted) && deptFormControl.DepartmentName.errors?.required">
                            Department Name is required
                        </div>
                    </div>
                    <hr />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button type="submit" 
                                    class="btn btn-success">
                                    Edit Department
                                </button>
                            </div>
                            <div class="col-sm-2">
                                <button type="button" 
                                    (click)="resetDept()" 
                                    class="btn btn-primary">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
