// reactapp-uadmin/src/components/Student_MyAssignments/Student_MyAssignments.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import StudentService from "../../services/student.service";
import {
  convertAsmtStatus,
  getAsmtStatusClass,
} from "../../services/local.service";
import { useNavigate, useLocation } from "react-router";

import Moment from "moment";

const Student_MyAssignments = () => {
  let navigate = useNavigate();
  // let { id } = useParams();

  const { state } = useLocation();
  const { studentId, firstName, lastName, courseId } = state; // Read values passed on state

  const [myAsmts, setMyAsmts] = useState([]);
  const [asmtLinkStatusClass, setAsmtLinkStatusClass] = useState("");

  const [asmtToDownload, setAsmtToDownload] = useState(null);
  const [downloadMsg, setDownloadMsg] = useState("");
  const [downloadClass, setDownloadClass] = useState("");

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Student"))
      navigate("/un-auth");
    else {
      console.log(studentId, firstName, lastName, courseId);
      loadAsmtsForStudentCourse();
    }
  }, []);

  const loadAsmtsForStudentCourse = () => {
    var stdCrsData = {
      studentId: studentId,
      courseId: courseId,
    };
    StudentService.loadAsmtsForStudentCourse(stdCrsData)
      .then((response) => {
        setMyAsmts(response.data);
        console.log(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  const downloadAssignment = (e, asmt, index) => {
    setAsmtToDownload(asmt.asmtFileName);

    var stdToAsmtDownload = {
      studentId: studentId,
      assignmentId: asmt.assignmentId,
      asmtFileName: asmt.asmtFileName,
    };
    console.log(stdToAsmtDownload);

    StudentService.downloadAsmt(stdToAsmtDownload)
      .then((blob) => {
        console.log(blob);

        setDownloadMsg(
          "Downloading..." + asmt.asmtFileName.substring(0, 35) + " !"
        );
        setDownloadClass("greenClass");

        // const myFile = new Blob([blob.data], { type: 'text/csv' });
        const myFile = new Blob([blob.data], { type: "application/pdf" });
        const url = window.URL.createObjectURL(myFile);
        window.open(url);

        setTimeout(() => {
          setAsmtToDownload(null);
          setDownloadMsg("");
          setDownloadClass("");
        }, 4000);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 500) {
          setDownloadMsg("Server Error !");
        } else if (e.response.status === 400) {
          setDownloadMsg("File Not Found !");
        } else {
          setDownloadMsg("Error while downloading assignment file !");
        }
        setDownloadClass("redClass");

        setTimeout(() => {
          setAsmtToDownload(null);
          setDownloadMsg("");
          setDownloadClass("");
        }, 4000);
      });
  };

  const submitAssignment = (e, asmt, index) => {
    var stdToAsmt = {
      studentId: studentId,
      assignmentId: asmt.assignmentId,
      courseId: courseId,
      firstName: firstName,
      lastName: lastName
    };
    navigate("/submit-assignment", {
      state: stdToAsmt,
    });
  };
  const checkAsmtLinkStatus = (a) => {
    if (a.asmtLinkStatus === 2) return false;
    else return true;
  };

  const renderAllAssignments = () => {
    return myAsmts.map((dt, i) => {
      return (
        <div key={i}>
          <div className="card">
            <div className="card-header">
              <div className="row asmtInfo">
                <div className="col-md-6 mx-auto ">
                  {dt.courseName}
                  <br />
                  <span className={`${getAsmtStatusClass(dt.asmtLinkStatus)}`}>
                    {convertAsmtStatus(dt.asmtLinkStatus)}
                  </span>
                </div>
                <div className="col-md-6 mx-auto">
                  {dt.asmtFileName}
                  <br />
                  <div className="row">
                    {checkAsmtLinkStatus(dt) && (
                      <div className="col-md-6 mx-auto ">
                        <Button
                          className="btn btn-info"
                          type="button"
                          onClick={(e) => downloadAssignment(e, dt, i)}
                        >
                          Download Assignment
                        </Button>
                        <br />
                        {asmtToDownload &&
                          asmtToDownload === dt.asmtFileName && (
                            <span className={downloadClass}>{downloadMsg}</span>
                          )}
                      </div>
                    )}

                    {checkAsmtLinkStatus(dt) && (
                      <div className="col-md-6 mx-auto ">
                        <Button
                          className="btn btn-success"
                          type="button"
                          onClick={(e) => submitAssignment(e, dt, i)}
                        >
                          Submit Assignment
                        </Button>
                      </div>
                    )}
                    <p></p>
                  </div>
                </div>
              </div>
            </div>
            <div className="card-body">
              Assignment : {dt.assignmentId} # {dt.title}
              <br />
              Details : {dt.details}
              <br />
              Submission Date : {Moment(dt.asmtLastDate).format("DD-MMM YYYY")}
            </div>
          </div>
          <hr />
        </div>
      );
    });
  };

  return (
    <div className="container">
      <div className="mainHeader">My-Assignments</div>
      <p></p>
      <div className="row">
        <div className="col-md-3 mx-auto"></div>
        <div className="col-md-6 mx-auto">
          <div className="studentHeader">
            # {studentId} ) {firstName}, {lastName}
          </div>
        </div>
        <div className="col-md-3 mx-auto"></div>
      </div>
      <p></p>
      <div className="row">
        <div className="col-md-12 mx-auto">
          <div>{myAsmts && myAsmts.length > 0 && renderAllAssignments()}</div>
        </div>
      </div>
    </div>
  );
};

export default Student_MyAssignments;

// NgApp/src/app/student-my-assignments/student-my-assignments.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import AsmtCrsStd from '../models/asmtCrsStd';
import AsmtFacDept from '../models/asmtFacDept';
import StdToAsmtDownload from '../models/stdToAsmtDownload';
import Student from '../models/student';
import { DataService } from '../services/data.service';
import { LocalDataService } from '../services/local-data.service';

@Component({
  selector: 'app-student-my-assignments',
  templateUrl: './student-my-assignments.component.html',
  styleUrls: ['./student-my-assignments.component.css']
})
export class StudentMyAssignmentsComponent implements OnInit {

  // view student's details
  studentModel = new Student();

  errorMessage = '';

  // view / download assignments of student 
  stdToAsmts: Array<AsmtCrsStd> = [];

  // download assignment
  stdToAsmtDownload = new StdToAsmtDownload();

  // check if file exists or not
  downloadStatus: string;
  downloadClass: string;
  downloadFile: string;

  constructor(private route: ActivatedRoute, public localDataService: LocalDataService, public dataService: DataService, public router: Router) {
  }

  // ok
  ngOnInit(): void {
    this.route.queryParams.subscribe(
      params => {
        try {
          this.studentModel = JSON.parse(params['student']);
          this.loadAsmtsForStudentCourse(this.studentModel.studentId, this.studentModel.courseId);

          console.log(this.studentModel);
        }
        catch (error) {
          this.errorMessage = 'Error in Parsing in-coming student data!';
        }
      }
    )
  }
  // ok
  // this will load assignments of selected course to respective student 
  loadAsmtsForStudentCourse(stdId, crsId) {
    this.dataService.loadAsmtsForStudentCourse(stdId, crsId)
      .subscribe(
        data => {
          this.stdToAsmts = data;
          console.log(data);
        },
        error => {
          console.log(error);
        }
      );
  }

  // ok
  convertAsmtStatus(statusCode) {
    if (statusCode == 0)
      return 'Assignment Linked';
    else if (statusCode == 1)
      return 'Assignment Not Linked';
    else
      return 'Assignment Submitted';
  }

  // ok
  public downloadAsmt(assignment) {
    console.log(assignment.asmtFileName);

    this.stdToAsmtDownload.studentId = this.studentModel.studentId;
    this.stdToAsmtDownload.assignmentId = assignment.assignmentId;
    this.stdToAsmtDownload.asmtFileName = assignment.asmtFileName;

    this.dataService.downloadAsmt(this.stdToAsmtDownload)
      .subscribe(blob => {

        // file exists and downloading
        this.setFileDownload('Downloading!', 'green', assignment.asmtFileName);

        console.log(blob);

        // const myFile = new Blob([blob], { type: 'text/csv' });
        const myFile = new Blob([blob], { type: 'application/pdf' });
        const url = window.URL.createObjectURL(myFile);
        window.open(url);

        setTimeout(() => {
          this.resetAfterFileDownload();

          // refresh assignments belong to selected course of student
          this.loadAsmtsForStudentCourse(this.studentModel.studentId, this.studentModel.courseId);
        }, 20000);
      }, error => {
        if (error.status == 400) {
          this.setFileDownload('File Not Found!', 'red', assignment.asmtFileName);

          console.log('File Not Found on Server!');

          setTimeout(() => {
            this.resetAfterFileDownload();
          }, 2000);
        }
        else {
          this.setFileDownload('Error!', 'red', assignment.asmtFileName);

          console.log("Error while downloading assignment file!");

          setTimeout(() => {
            this.resetAfterFileDownload();
          }, 2000);
        }
      });
  }
  // ok
  setFileDownload(downloadStatus, downloadClass, downloadFile) {
    this.downloadStatus = downloadStatus;
    this.downloadClass = downloadClass;
    this.downloadFile = downloadFile;
  }
  // ok
  resetAfterFileDownload() {
    this.downloadStatus = '';
    this.downloadClass = '';
    this.downloadFile = '';
  }

  // ok
  public uploadFinished = (event) => {
    console.log('Assignment Submit OK!');

    // refresh assignments belong to selected course of student
    this.loadAsmtsForStudentCourse(this.studentModel.studentId, this.studentModel.courseId);
  }

  // ok
  // true means download and submit options are enabled
  // false means already donloaded and submitted, so download and submit options are disabled
  checkAsmtLinkStatus(assignment) {
    if (assignment.asmtLinkStatus == 2) {
      return false;
    }
    else {
      return true;
    }
  }
}

<div class="container">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">
                <div class="card-header" 
                    style="background-color: lightyellow;">
                    <h3>
                        <div *ngIf="errorMessage" 
                            style="color:red;">
                            {{errorMessage}}
                        </div>
                        <div *ngIf="!errorMessage">
                            # {{studentModel.studentId}} ) {{studentModel.firstName}},
                            {{studentModel.lastName}}
                        </div>
                        <hr />
                    </h3>
                </div>
                <div *ngIf="!errorMessage" class="card-body">
                    <div class="container">
                        <div class="col-md-12 mx-auto">
                            <div class="card">
                                <div class="card-header" 
                                    style="background-color:whitesmoke;">
                                    <h4>
                                        Assignments
                                        <span style=" color: red; font-size: medium; margin-left: 100px;">
                                            Download Assignments (OR) Submit Assignments
                                        </span>
                                    </h4>
                                </div>
                                <div class="card-body" 
                                    style="background-color:white;">
                                    <div *ngIf="stdToAsmts?.length>0; else noAsmts">
                                        <div *ngFor="let a of stdToAsmts">
                                            <div class="card">
                                                <div class="card-header" 
                                                    style="background-color: lightskyblue;">
                                                    <div class="row">
                                                        <div class="col-5">
                                                            <h5>
                                                                {{a.courseName}}
                                                                <div *ngIf="a.asmtLinkStatus==0" style="color:green;">
                                                                    {{convertAsmtStatus(a.asmtLinkStatus)}}
                                                                </div>
                                                                <div *ngIf="a.asmtLinkStatus==1" style="color:red;">
                                                                    {{convertAsmtStatus(a.asmtLinkStatus)}}
                                                                </div>
                                                                <div *ngIf="a.asmtLinkStatus==2" style="color:blue;">
                                                                    {{convertAsmtStatus(a.asmtLinkStatus)}}
                                                                </div>
                                                            </h5>
                                                        </div>
                                                        <div *ngIf="a.asmtFileName" class="col-7">
                                                            {{a.asmtFileName}}
                                                            <p></p>
                                                            <div class="row">
                                                                <div *ngIf="checkAsmtLinkStatus(a)" class="col-6">
                                                                    <button type="button" (click)="downloadAsmt(a)" class="btn btn-primary">
                                                                        Download Assignment
                                                                    </button>
                                                                </div>
                                                                <div *ngIf="checkAsmtLinkStatus(a)" class="col-6">
                                                                    <!-- asmt submit control -->
                                                                    <app-submit-asmt [assignmentId]="a.assignmentId" [studentId]="studentModel.studentId"
                                                                        (onUploadFinished)="uploadFinished($event)">
                                                                    </app-submit-asmt>
                                                                </div>
                                                            </div>
                                                            <span 
                                                                *ngIf="downloadStatus && downloadFile==a.asmtFileName" [style.color]="downloadClass">
                                                                <p>
                                                                    {{downloadStatus}}
                                                                </p>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card-body">
                                                Assignment : {{a.assignmentId}} # {{a.title}}
                                                <p></p>
                                                Details : {{a.details}}
                                                <p></p>
                                                Submission Date : {{a.asmtLastDate | date : "dd-MMM-y"}}
                                            </div>
                                            <div class="card-footer">
                                            </div>
                                        </div>
                                    </div>
                                   
                                    <ng-template #noAsmts>
                                        <div class="noAsmts">
                                            You Do Not have any Assignment To Download OR Submit !!!
                                        </div>
                                    </ng-template>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
