// ngApp/src/app/assignment/assignment.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import Assignment from '../models/assignment';
import { Observable } from 'rxjs';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import FacultyList from '../models/facultyList';
import AssignmentCreate from '../models/assignmentCreate';
import AsmtFacDept from '../models/asmtFacDept';
import Department from '../models/department';


@Component({
  selector: 'app-assignment',
  templateUrl: './assignment.component.html',
  styleUrls: ['./assignment.component.css']
})
export class AssignmentComponent implements OnInit {

  departments: Array<Department>;
  faculties: Array<FacultyList>;
  assignments: Array<AsmtFacDept>;

  asmtForm: FormGroup;
  submitted = false;
  assignmentModel = new AssignmentCreate();
  newAsmtAddPanel = false;

  apiResponse = '';
  responseColor = '';

  asmtDetailsPanel = false;

  // search form
  searchForm: FormGroup;
  filteredAssignments: Array<AsmtFacDept>;
  searchEnabled = false;
  facs: Array<FacultyList> = [];
  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router) { }

  // ok
  ngOnInit() {

    this.asmtForm = this.fb.group({
      Title: ['', Validators.required],
      Details: ['', Validators.required],
      DepartmentId: ['', Validators.required],
      FacultyId: ['', Validators.required],
      AsmtLastDate: ['', Validators.required]
    })

    this.loadDept();

    this.loadAsmtFacDept();


    this.searchForm = this.fb.group({    
      SDepartmentId: [''],
      SFacultyId: ['']
    })
  }  

  // wip
  // search by department
  searchBy(){
    var selectedDepartmentId = Number(this.searchForm.value["SDepartmentId"]);      
    var selectedFacultyId = Number(this.searchForm.value["SFacultyId"]);
    if(selectedDepartmentId<=0 && selectedFacultyId<=0){
      return;
    }
    else{
      console.log('department : ' + selectedDepartmentId);
      console.log('faculty : ' + selectedFacultyId);
      var filterByDepartment = this.assignments.filter(xx => xx.departmentId == selectedDepartmentId);
      this.filteredAssignments = this.assignments.filter(xx => xx.departmentId == selectedDepartmentId);
      console.log(this.filteredAssignments);
      // OR condition between department and faculty filter
      var filterByFaculty = this.assignments.filter(xx => xx.facultyId == selectedFacultyId);
      this.filteredAssignments = this.assignments.filter(xx => xx.facultyId == selectedFacultyId);
      console.log(this.filteredAssignments);

      this.searchEnabled = true;
    }
    
  }
  // displays faculties belong to all assignments in db
  // no api call
  // displays unique list of faculties from current list of assignments
  displayFacs() {
    const map = new Map();
    for (const item of this.assignments) {
      if (!map.has(item.facultyId)) {
        map.set(item.facultyId, true);
        this.facs.push({
          facultyId: item.facultyId,
          facultyName: item.facultyName
        });
      }
    }
  }
  // reset filter
  clearAllFilter(){
    this.searchEnabled = false;
    this.searchForm.reset();
  }





  // ok
  // format fac. / dept. column
  formatingFacDeptName(a){
    var editedFacName = '';
    var editedDeptName = '';

    // faculty name
    if(a.facultyName.length>=8){
      editedFacName = a.facultyName.substring(0, 7) +'...';
    }
    else{
      editedFacName = a.facultyName;
    }

    // department name
    if (a.departmentName.length >= 6) {
      editedDeptName = a.departmentName.substring(0, 5) + '...';
    }
    else {
      editedDeptName = a.departmentName;
    }

    return editedFacName + ' / ' + editedDeptName;
  }

  // ok
  // format details column
  formatingDetails(a) {
    var editedDetails = '';

    if (a.details.length >= 21) {
      editedDetails = a.details.substring(0, 20) + '...';
    }
    else {
      editedDetails = a.details;
    }

    return editedDetails;
  }

  // ok
  changeDepartment(e) {
    this.loadFacs(e.target.value);
  }

  // ok
  loadDept(){
    this.dataService.getDepartments()
      .subscribe(
        data => {
          this.departments = data;
        },
        error => {
          console.log(error);
        });
  }

  // ok
  loadAsmtFacDept(){
    this.dataService.getAssignments()
      .subscribe(
        data => {
          this.assignments = data;


          this.displayFacs();
        },
        error => {
          console.log(error);
        });
  }
  
  // ok
  // displays faculties belong to selected department
  loadFacs(selectedDeptId) {
    this.dataService.listOfFaculties(selectedDeptId)
      .subscribe(
        data => {
          if(data.length<=0){
            // reset facultyId select list control
            this.asmtForm.controls['FacultyId'].setValue('');
          }
          this.faculties = data;
        },
        error => {
          console.log(error);
        });
  }

  // ok
  addAsmt() {
    this.newAsmtAddPanel = true;
  }

  // ok
  get asmtFormControl() {
    return this.asmtForm.controls;
  }

  // ok
  onSubmit(): void {

    console.log(this.asmtForm.value["AsmtLastDate"].year);

    this.submitted = true;
    if (this.asmtForm.valid) {
      this.assignmentModel.title = this.asmtForm.value["Title"];
      this.assignmentModel.details = this.asmtForm.value["Details"];
      this.assignmentModel.facultyId = Number(this.asmtForm.value["FacultyId"]);
      this.assignmentModel.asmtLastDate = new Date( this.asmtForm.value["AsmtLastDate"].year + '/' + this.asmtForm.value["AsmtLastDate"].month + '/' + this.asmtForm.value["AsmtLastDate"].day);
      this.assignmentModel.asmtCreateDate = new Date();

      // retrive asmtUploadId from local-data service
      this.assignmentModel.asmtUploadId = this.localDataService.getAsmtUploadId();

      this.dataService.addAsmt(this.assignmentModel)
        .subscribe(
          res => {
            if (res.responseCode == 0) {
              // success
              this.apiResponse = res.responseMessage;
              this.responseColor = 'green';
              this.newAsmtAddPanel = false;
              this.asmtDetailsPanel = false;
              this.submitted = false;
              this.asmtForm.reset();
              this.localDataService.setAsmtUploadId(0);

              // clear success message after 3 seconds
              setTimeout(() => {
                this.apiResponse = '';
              }, 3000);

              this.loadAsmtFacDept();
            }
            else {
              // fail
              // display error message
              this.apiResponse = res.responseCode + ' : ' + res.responseMessage;
              this.responseColor = 'red';
              this.newAsmtAddPanel = true;
              this.asmtDetailsPanel = true;
            }
          },
          error => {
            this.apiResponse = error;
            this.responseColor = 'red'; 
            this.newAsmtAddPanel = true;
            this.asmtDetailsPanel = true;
          }
        );
    }
  }

  // ok
  resetAsmt() {
    this.newAsmtAddPanel = false;
    this.apiResponse = '';
    this.asmtForm.reset();
    this.submitted = false;
    this.localDataService.setAsmtUploadId(0);

    this.asmtDetailsPanel = false;
  }
  
  // ok
  public uploadFinished = (event) => {
    console.log('upload done...');
    // console.log('assignment upload id... '+ event.model.asmtUploadId);
    // console.log('file name... ' + event.model.fileName);

    // 2 different processes
    // 1. assignment file upload - AsmtUploads table
    // 2. other assignment details(title/details) add - Assignments table
    // store asmtUploadId to local-data service
    // so other assignment details(title/details) get consistent with 
    // assignment file upload,,,
    // which is the next process just right after assignment file upload
    this.localDataService.setAsmtUploadId(event.model.asmtUploadId);

    // make visible asmtDetailsPanel 
    this.asmtDetailsPanel = true;
  }  

  // ok
  public downloadAsmt(assignment){
    console.log(assignment.asmtFileName);
    this.dataService.download(assignment.asmtFileName)
      .subscribe(blob => {
        console.log(blob);

        // const myFile = new Blob([blob], { type: 'text/csv' });
        const myFile = new Blob([blob], { type: 'application/pdf' });
        const url = window.URL.createObjectURL(myFile);
        window.open(url);
      }, error => {
        console.log("Error while downloading assignment file!");
      });
  }

  // ok
  cancel(){
    this.newAsmtAddPanel = false;
    this.asmtDetailsPanel = false;
  }  
}

<div class="container">
    <div class="row">
        <div class="col-md-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>
                        <div>
                            Assignment
                        </div>
                        <hr />
                        <h4 *ngIf="apiResponse">
                            <span [style.color]="responseColor">
                                {{apiResponse}}
                            </span>
                        </h4>  
                    </h3> 
                    <div class="row" *ngIf="!newAsmtAddPanel">
                        <div class="col-4">
                            <button type="button" 
                                (click)="addAsmt()" 
                                class="btn btn-success">Add Assignment
                            </button>
                        </div>
                        <div class="col-8">
                            <div class="card">
                                <div class="card-header">
                                    <h4>
                                        Serach Panel
                                        <!-- this will remove all filter conditions and default load all assignments -->
                                        <button type="button" 
                                            (click)="clearAllFilter()" 
                                            class="btn btn-success">
                                                Clear All Filter
                                        </button>
                                    </h4>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-6">
                                            <form class="form-search" 
                                                [formGroup]="searchForm">
                                                <!-- department list -->
                                                <div class="form-group">
                                                    <label>Department : </label>
                                                    <select class="form-control" 
                                                        formControlName="SDepartmentId">
                                                        <option disabled>Select Department</option>
                                                        <option value={{d.departmentId}} 
                                                            *ngFor="let d of departments">
                                                            {{d.departmentName}}
                                                        </option>
                                                    </select>
                                                </div>
                                                <!-- faculty list -->
                                                <div class="form-group">
                                                    <label>Faculty : </label>
                                                    <select class="form-control" 
                                                        formControlName="SFacultyId">
                                                        <option disabled>Choose Faculty</option>
                                                        <option value={{f.facultyId}} 
                                                            *ngFor="let f of facs">
                                                            {{f.facultyName}}
                                                        </option>
                                                    </select>                                                
                                                </div>
                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="col-sm-6">
                                                            <button type="button" 
                                                                (click)="searchBy()" 
                                                                class="btn btn-success">
                                                                Search
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <div class="card-body">
                    <div class="container" *ngIf="newAsmtAddPanel">
                        <div class="col-md-7 mx-auto">
                            <div class="card">
                                <div class="card-header">
                                    <div class="row">
                                        <div class="col-8">
                                            <!-- file upload control -->
                                            <app-upload 
                                                (onUploadFinished)="uploadFinished($event)">
                                            </app-upload>
                                        </div>
                                        <div class="col-4">
                                            <button type="button" 
                                                (click)="cancel()" 
                                                class="btn btn-primary">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>                               
                                </div>
                                <div class="card-body">
                                    <form *ngIf="asmtDetailsPanel" 
                                        class="form-asmt" 
                                        [formGroup]="asmtForm" 
                                        (ngSubmit)="onSubmit()">
                                        <div class="form-group">
                                            <label>Title</label>
                                            <input type="text" class="form-control" formControlName="Title">
                                            <div *ngIf="submitted && asmtFormControl.Title.errors?.required" 
                                                class="alert alert-danger mt-2">
                                                Title Required
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Details</label>
                                            <input type="text" class="form-control" 
                                                formControlName="Details">                                          
                                            <div *ngIf="submitted && asmtFormControl.Details.errors?.required" 
                                                class="alert alert-danger mt-2">
                                                Details Required
                                            </div>
                                        </div>

                                        <!-- date complexity -->
                                        <div class="form-group">
                                            <label>Asmt. Last Submission Date</label>
                                            <div class="input-group">
                                                <input class="form-control" 
                                                    placeholder="yyyy-mm-dd" 
                                                    name="dp" formControlName="AsmtLastDate" 
                                                    ngbDatepicker
                                                    #d="ngbDatepicker">
                                                <div class="input-group-append">
                                                    <button class="btn btn-outline-secondary calendar" 
                                                    (click)="d.toggle()" type="button"></button>
                                                </div>
                                            </div>
                                            <div *ngIf="submitted && asmtFormControl.AsmtLastDate.errors?.required" 
                                                class="alert alert-danger mt-2">
                                                Assignment Last Submission Date Required
                                            </div>
                                        </div>
                                  

                                        <!-- department list -->
                                        <div class="form-group">
                                            <label>Department : </label>
                                            <select class="form-control" 
                                                (change)="changeDepartment($event)"
                                                formControlName="DepartmentId">
                                                <option value="">Choose Department</option>
                                                <option value={{d.departmentId}} 
                                                    *ngFor="let d of departments">
                                                    {{d.departmentName}}
                                                </option>
                                            </select>                                         
                                            <div *ngIf="submitted && asmtFormControl.DepartmentId.errors?.required" 
                                                class="alert alert-danger mt-2">
                                                Please choose Department
                                            </div>
                                        </div>

                                        <!-- faculty list -->
                                        <div class="form-group">
                                            <label>Faculty : </label>
                                            <select class="form-control" 
                                                formControlName="FacultyId">     
                                                <option disabled>Choose Faculty</option>
                                                <option value="">Choose Faculty</option>                                                
                                                <option value={{f.facultyId}} 
                                                    *ngFor="let f of faculties">
                                                    {{f.facultyName}}
                                                </option>
                                            </select>                                          
                                            <div *ngIf="submitted && asmtFormControl.FacultyId.errors?.required" 
                                                class="alert alert-danger mt-2">
                                                Please choose Faculty
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <button type="submit" class="btn btn-success">
                                                        New Assignment
                                                    </button>
                                                </div>
                                                <div class="col-sm-6">
                                                    <button type="button" 
                                                        data-toggle="tooltip" 
                                                        title="If you Cancel, then you will loose any uploaded document!"
                                                        (click)="resetAsmt()"
                                                        class="btn btn-primary">
                                                        Cancel
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <p></p>
                    </div>


                <!-- if search is enabled -->
                <div *ngIf="searchEnabled" class="col-md-10 mx-auto">
                    <div *ngFor="let a of filteredAssignments">
                        <div class="card">
                            <div class="card-header" style="background-color: lightcoral;">
                                <h5>
                                    Department : {{a.departmentId}} # {{a.departmentName}}
                                    <p></p>
                                    Faculty : {{a.facultyName}}
                                </h5>
                            </div>
                            <div class="card-body">
                                Assignment : {{a.assignmentId}} # {{a.title}}
                                <p></p>
                                Details : {{a.details}}
                                <p></p>
                                Submission Date : {{a.asmtLastDate | date : "dd-MMM-y"}}
                            </div>
                            <div class="card-footer">
                                Assignment File : {{a.asmtFileName}}
                                <p></p>
                                <button type="button" (click)="downloadAsmt(a)" class="btn btn-primary">
                                    Download
                                </button>
                            </div>
                        </div>
                        <hr />
                    </div>
                </div>
                    
                <!-- if search is not enabled -->
                <div *ngIf="!searchEnabled" class="col-md-10 mx-auto">
                    <div *ngFor="let a of assignments">
                        <div class="card">
                            <div class="card-header" 
                                style="background-color: lightcoral;">
                                <h5>
                                    Department : {{a.departmentId}} # {{a.departmentName}}
                                    <p></p>
                                    Faculty : {{a.facultyName}}
                                </h5>
                            </div>
                            <div class="card-body">
                                Assignment : {{a.assignmentId}} # {{a.title}}
                                <p></p>
                                Details : {{a.details}} 
                                <p></p>
                                Submission Date : {{a.asmtLastDate | date : "dd-MMM-y"}}
                            </div>
                            <div class="card-footer">
                                Assignment File : {{a.asmtFileName}}
                                <p></p>
                                <button type="button" 
                                    (click)="downloadAsmt(a)" 
                                    class="btn btn-primary">
                                    Download
                                </button>                            
                            </div>                          
                        </div>
                        <hr />
                    </div>                 
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-uadmin/src/components/Assignment/Assignment.jsx
import React, { useState, useEffect, useRef } from "react";
import "./style.css";
import AuthService from "../../services/auth.service";
import AssignmentService from "../../services/assignment.service";
import DepartmentService from "../../services/department.service";
import { useNavigate } from "react-router-dom";

// react-bootstrap-table-2
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import filterFactory, { textFilter } from "react-bootstrap-table2-filter";

import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";

import Moment from "moment";

const Assignment = () => {
  let navigate = useNavigate();

  const [assignments, setAssignments] = useState([]);

  // download assignment
  const [asmtToDownload, setAsmtToDownload] = useState(null);
  const [downloadMsg, setDownloadMsg] = useState("");
  const [downloadClass, setDownloadClass] = useState("");

  // search
  const [assignments_, setAssignments_] = useState([]);
  const [enableSearch, setEnableSearch] = useState(false);
  const [facs, setFacs] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [form, setForm] = useState({});
  // reset form
  // form reference
  const formRef = useRef(null);

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      getAllAssignments();
    }
  }, []);

  const getAllAssignments = () => {
    AssignmentService.allAsmtFacDept()
      .then((response) => {
        console.log(response.data);
        setAssignments(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        }
      });
  };

  const createNewAssignment = (e) => {
    console.log("create new assignment!");
  };
  const downloadAssignment = (e, asmt, index) => {
    console.log("download assignment # ", asmt.assignmentId, asmt.asmtUploadId);
    setAsmtToDownload(asmt.asmtFileName);

    AssignmentService.asmtDownload(asmt.asmtFileName)
      .then((blob) => {
        console.log(blob);
        setDownloadMsg(
          "Downloading..." + asmt.asmtFileName.substring(0, 35) + " !"
        );
        setDownloadClass("greenClass");

        // const myFile = new Blob([blob.data], { type: 'text/csv' });
        const myFile = new Blob([blob.data], { type: "application/pdf" });
        const url = window.URL.createObjectURL(myFile);
        window.open(url);

        setTimeout(() => {
          setAsmtToDownload(null);
          setDownloadMsg("");
          setDownloadClass("");
        }, 4000);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 500) {
          setDownloadMsg("Server Error !");
        } else if (e.response.status === 400) {
          setDownloadMsg("File Not Found !");
        }
        setDownloadClass("redClass");

        setTimeout(() => {
          setAsmtToDownload(null);
          setDownloadMsg("");
          setDownloadClass("");
        }, 4000);
      });
  };

  const renderAllAssignments = () => {
    return assignments.map((dt, i) => {
      return (
        <div key={i}>
          <div className="card">
            <div className="card-header">
              <div className="row">
                <div className="col-md-6 mx-auto asmtInfo">
                  {dt.departmentName} / {dt.courseName}
                  <br />
                  Faculty : {dt.facultyName}
                </div>
                <div className="col-md-6 mx-auto">
                  {dt.asmtFileName}
                  <br />
                  <Button
                    className="btn btn-info"
                    type="button"
                    onClick={(e) => downloadAssignment(e, dt, i)}
                  >
                    Download Assignment
                    {/* 
                    <a
                      href={
                        "https://localhost:44354/api/Assignment/download?fileName=" +
                        dt.asmtFileName
                      }
                    >
                      Download Assignment
                    </a>
                    */}
                  </Button>
                  <br />
                  {asmtToDownload && asmtToDownload === dt.asmtFileName && (
                    <span className={downloadClass}>{downloadMsg}</span>
                  )}
                </div>
              </div>
            </div>
            <div className="card-body">
              Assignment : {dt.assignmentId} # {dt.title}
              <br />
              Details : {dt.details}
              <br />
              Submission Date : {Moment(dt.asmtLastDate).format("DD-MMM YYYY")}
            </div>
          </div>
          <hr />
        </div>
      );
    });
  };

  // search
  // displays faculties belong to all assignments in db
  // no api call
  // displays unique list of faculties from current list of assignments
  const displaySearchPanel = (e) => {
    loadAllDepartments();
    refreshFacs();
    setEnableSearch(true);
  };
  const refreshFacs = () => {
    setFacs([]);
    let facs_ = [];
    const map = new Map();
    for (const item of assignments) {
      if (!map.has(item.facultyId)) {
        map.set(item.facultyId, true);
        facs_.push({
          facultyId: item.facultyId,
          facultyName: item.facultyName,
        });
      }
    }
    setFacs(facs_);
    console.log(facs);
  };
  const loadAllDepartments = () => {
    DepartmentService.allDepartments()
      .then((response) => {
        console.log(response.data);
        setDepartments(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };
  const setField = (field, value) => {
    setForm({
      ...form,
      [field]: value,
    });
  };
  const resetForm = (e) => {
    setAssignments_([]);
    formRef.current.reset();
    setForm({});
    setEnableSearch(false);
  };
  const renderOptionsForDepartments = () => {
    return departments.map((dt, i) => {
      return (
        <option value={dt.departmentId} key={i} name={dt.departmentName}>
          {dt.departmentName}
        </option>
      );
    });
  };
  const renderOptionsForFaculties = () => {
    return facs.map((dt, i) => {
      return (
        <option value={dt.facultyId} key={i} name={dt.facultyName}>
          {dt.facultyName}
        </option>
      );
    });
  };
  const searchBy = (e) => {
    let filteredAssignmentsByDepartments = [];
    let filteredAssignmentsByFaculties = [];
    let filteredByDeptAndFac = [];
    if (form.departmentId !== null || form.departmentId !== "") {
      filteredAssignmentsByDepartments = assignments.filter(
        (xx) => xx.departmentId === Number(form.departmentId)
      );
    }
    if (form.facultyId !== null || form.facultyId !== "") {
      filteredAssignmentsByFaculties = assignments.filter(
        (xx) => xx.facultyId === Number(form.facultyId)
      );
    }

    // first combine filterByDepartment and filterByFaculty
    filteredByDeptAndFac = [
      ...filteredAssignmentsByDepartments,
      ...filteredAssignmentsByFaculties,
    ];

    const key = "assignmentId";
    const arrayUniqueByKey = [
      ...new Map(
        filteredByDeptAndFac.map((item) => [item[key], item])
      ).values(),
    ];
    console.log(arrayUniqueByKey);
    setAssignments_(arrayUniqueByKey);
  };
  const renderAllAssignments_ = () => {
    return assignments_.map((dt, i) => {
      return (
        <div key={i}>
          <div className="card">
            <div className="card-header">
              <div className="row">
                <div className="col-md-6 mx-auto asmtInfo">
                  {dt.departmentName} / {dt.courseName}
                  <br />
                  Faculty : {dt.facultyName}
                </div>
                <div className="col-md-6 mx-auto">
                  {dt.asmtFileName}
                  <br />
                  <Button
                    className="btn btn-info"
                    type="button"
                    onClick={(e) => downloadAssignment(e, dt, i)}
                  >
                    Download Assignment
                    {/* 
                    <a
                      href={
                        "https://localhost:44354/api/Assignment/download?fileName=" +
                        dt.asmtFileName
                      }
                    >
                      Download Assignment
                    </a>
                    */}
                  </Button>
                  <br />
                  {asmtToDownload && asmtToDownload === dt.asmtFileName && (
                    <span className={downloadClass}>{downloadMsg}</span>
                  )}
                </div>
              </div>
            </div>
            <div className="card-body">
              Assignment : {dt.assignmentId} # {dt.title}
              <br />
              Details : {dt.details}
              <br />
              Submission Date : {Moment(dt.asmtLastDate).format("DD-MMM YYYY")}
            </div>
          </div>
          <hr />
        </div>
      );
    });
  };

  return (
    <div className="container">
      <div className="mainHeader">Assignments</div>
      <hr />
      <div className="row">
        <div className="col-md-12 mx-auto">
          <div className="card">
            <div className="card-header header">
              <div className="row">
                <div className="col-md-4 mx-auto">
                  <Button
                    className="btn btn-success"
                    type="button"
                    onClick={(e) => createNewAssignment(e)}
                  >
                    Create New Assignment
                  </Button>
                </div>
                <div className="col-md-8 mx-auto">
                  {!enableSearch && (
                    <div>
                      <Button
                        className="btn btn-info"
                        type="button"
                        onClick={(e) => displaySearchPanel(e)}
                      >
                        S.E.A.R.C.H
                      </Button>
                      <p></p>{" "}
                    </div>
                  )}

                  {enableSearch && (
                    <Form ref={formRef}>
                      <div className="row searchPanel">
                        <div className="col-md-4 mx-auto">
                          <Form.Group controlId="departmentId">
                            <Form.Label>Department</Form.Label>
                            <Form.Control
                              as="select"
                              onChange={(e) => {
                                setField("departmentId", e.target.value);
                              }}
                            >
                              <option value="">Select Department</option>
                              {renderOptionsForDepartments()}
                            </Form.Control>
                          </Form.Group>
                        </div>
                        <div className="col-md-4 mx-auto">
                          <Form.Group controlId="facultyId">
                            <Form.Label>Faculty</Form.Label>
                            <Form.Control
                              as="select"
                              onChange={(e) => {
                                setField("facultyId", e.target.value);
                              }}
                            >
                              <option value="">Select Faculty</option>
                              {renderOptionsForFaculties()}
                            </Form.Control>
                          </Form.Group>
                        </div>
                        <div className="col-md-4 mx-auto">
                          <div
                            style={{
                              display: "flex",
                              justifyContent: "space-between",
                            }}
                          >
                            <Button
                              className="btn btn-success"
                              type="button"
                              onClick={(e) => searchBy(e)}
                            >
                              Search
                            </Button>
                            <Button
                              className="btn btn-primary"
                              type="button"
                              onClick={(e) => resetForm(e)}
                            >
                              Reset
                            </Button>
                          </div>
                        </div>
                      </div>
                    </Form>
                  )}
                </div>
              </div>
            </div>
            <div className="card-body">
              {assignments_ && assignments_.length > 0
                ? renderAllAssignments_()
                : renderAllAssignments()}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Assignment;
