// NgApp/src/app/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import Student from '../models/student';
import { DataService } from '../services/data.service';
import { LocalDataService } from '../services/local-data.service';
import { UserService } from '../services/user.service';
import Validation from '../services/validation';


@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent implements OnInit {

  responseColor = '';
  errors: string[];
  
   form: FormGroup = new FormGroup({
    fullname: new FormControl(''),
    username: new FormControl(''),
    email: new FormControl(''),
    password: new FormControl(''),
    confirmPassword: new FormControl(''),
    acceptTerms: new FormControl(false),
  });
  submitted = false;

  students: Array<Student>;
  // controlls visibility of student select list
  showStudentList = false;

  registerModel = {
    UserName: '',
    FullName: '',
    Email: '',
    Password: '',
    StudentId: 0
  };
 
  constructor(
    private formBuilder: FormBuilder,
    public userService: UserService,
    public router: Router,
    public localDataService: LocalDataService,
    public dataService: DataService) { }

   ngOnInit(): void {
    this.form = this.formBuilder.group(
      {
        name: ['', Validators.required],
        username: [
          '',
          [
            Validators.required,
            Validators.minLength(6),
            Validators.maxLength(20)
          ]
        ],
        email: ['', [Validators.required, Validators.email]],
        password: [
          '',
          [
            Validators.required,
            Validators.minLength(6),
            Validators.maxLength(40)
          ]
        ],
        confirmPassword: ['', Validators.required],
        MyRole: ['', [Validators.required]],
        studentId: ['', [Validators.required]]
      },
      {
        validators: [Validation.match('password', 'confirmPassword')]
      }
    );

    if (this.userService.isLoggedIn) {
      // already logged in, so return to home page
      this.router.navigate(['/home']);
    }
    else {
      // not logged in yet
    }
    this.localDataService.setRegisterMessage('');
  }

  get f(): { [key: string]: AbstractControl } {
    return this.form.controls;
  }

  onSubmit(): void {
    
    this.responseColor = '';
    this.errors = [];    

    // to ignore validation for studentId select list
    // when Admin - role is selected
    if(this.showStudentList==false){      
      this.form.patchValue({
        studentId: 0
      });
    }

    this.submitted = true;

    if (this.form.invalid) {
      return;
    }

      // console.log(JSON.stringify(this.form.value, null, 2));
      this.registerModel.FullName = this.form.value["name"];
      
      this.registerModel.UserName = this.form.value["username"];
      
      // check for ModelState @api
      // this.registerModel.UserName = null;
      this.registerModel.Email = this.form.value["email"];
      this.registerModel.Password = this.form.value["password"];
      var MyRole = this.form.value["MyRole"];
      this.registerModel.StudentId = Number(this.form.value["studentId"]);
      
      this.userService.register(this.registerModel, MyRole).subscribe(
        res => {
          console.log(res);
          if (res.responseCode === 0) {
            // success
            this.onReset();
            this.responseColor = 'green';
            this.localDataService.setRegisterMessage(res.responseMessage);

            // redirect to login page
            setTimeout(() => {
              this.router.navigate(['/signin']);
            }, 3000); 
          }
          // -1
          else {
            this.responseColor = 'red';
            // fail
            this.localDataService.setRegisterMessage(res.responseMessage);
          }
        },
        error => {    
          this.responseColor = 'red';
          // 400
          // ModelState @api
          if (error.status === 400) {   
            this.errors = this.localDataService.display400andEx(error, 'Registration');      
          }
          // 500
          else{
            this.localDataService.setRegisterMessage(error.error.message);
          }
        }
      );
  }

  onReset(): void {
    this.submitted = false;
    this.form.reset();
    this.responseColor = '';
    this.errors = [];    
    this.localDataService.setRegisterMessage("");
  }

  // ok
  // when role is changed from select list
  changeRole(e) {
    // console.log(e.target.value);
    // if role is Student then load student select list
    // else return
    if(e.target.value=='Student'){
      // loading student select list
      this.showStudentList = true;
      this.loadStds();
    }
    else{
      this.showStudentList = false;
      return;
    }
  }

  // ok
  loadStds() {
    this.dataService.getStudentsNotLinkedToApplicationUser()
      .subscribe(
        data => {
          this.students = data;
          console.log(this.students);
        },
        error => {
          console.log(error);
        });
  }
}
<div class="container">
    <div class="row">
        <div class="col-md-7 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Registration</h3>
                    <h5 *ngIf="this.localDataService.getRegisterMessage()" 
                        [style.color]="responseColor">
                        {{this.localDataService.getRegisterMessage()}}
                    </h5>
                    <h5 *ngIf="errors?.length > 0">
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of errors">
                                {{ error }}
                            </li>
                        </ul>
                    </h5>
                </div>
                <div class="card-body">
                    <form [formGroup]="form" (ngSubmit)="onSubmit()">
                        
                        <!-- role -->
                        <div class="form-group">
                            <label>Role : </label>
                            <select class="form-control" 
                                (change)="changeRole($event)" 
                                [ngClass]="{ 'is-invalid': submitted && f['name'].errors }"
                                formControlName="MyRole">
                                <option disabled>Select Role</option>
                                <option value="">Choose Role</option>
                                <option value="Admin">Admin</option>
                                <option value="Student">Student</option>
                            </select>
                            <div *ngIf="submitted && f['MyRole'].errors" class="invalid-feedback">
                                <div *ngIf="f['MyRole'].errors['required']">Role is required</div>
                            </div>
                        </div>
                        <p></p>

                        <!-- student select list -->
                        <div *ngIf="showStudentList" class="form-group">
                            <label>Student : </label>
                            <select class="form-control" 
                                [ngClass]="{ 'is-invalid': submitted && f['studentId'].errors }"
                                formControlName="studentId">
                                <option disabled>Choose Student</option>
                                <option value="">Choose Student</option>
                                <option value={{s.studentId}} *ngFor="let s of students">
                                    {{s.firstName}}, {{s.lastName}}
                                </option>
                            </select>
                            <div *ngIf="submitted && f['studentId'].errors" 
                                class="invalid-feedback">
                                <div *ngIf="f['studentId'].errors['required']">Student is required</div>
                            </div>
                        </div>
                        <p></p>

                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" 
                                formControlName="name" class="form-control"
                                [ngClass]="{ 'is-invalid': submitted && f['name'].errors }" />
                            <div *ngIf="submitted && f['name'].errors" class="invalid-feedback">
                                <div *ngIf="f['name'].errors['required']">Name is required</div>
                            </div>
                        </div>
                        <p></p>
                    
                        <div class="form-group">
                            <label>User Name</label>
                            <input type="text" 
                                formControlName="username" class="form-control"
                                [ngClass]="{ 'is-invalid': submitted && f['username'].errors }" />
                            <div *ngIf="submitted && f['username'].errors" class="invalid-feedback">
                                <div *ngIf="f['username'].errors['required']">User Name is required</div>
                                <div *ngIf="f['username'].errors['minlength']">
                                    User Name must be at least 6 characters
                                </div>
                                <div *ngIf="f['username'].errors['maxlength']">
                                    User Name must not exceed 20 characters
                                </div>
                            </div>
                        </div>
                        <p></p>
                    
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" 
                                formControlName="email" class="form-control"
                                [ngClass]="{ 'is-invalid': submitted && f['email'].errors }" />
                            <div *ngIf="submitted && f['email'].errors" class="invalid-feedback">
                                <div *ngIf="f['email'].errors['required']">Email is required</div>
                                <div *ngIf="f['email'].errors['email']">Email is invalid</div>
                            </div>
                        </div>
                        <p></p>
                    
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" 
                                formControlName="password" 
                                class="form-control"
                                [ngClass]="{ 'is-invalid': submitted && f['password'].errors }" />
                            <div *ngIf="submitted && f['password'].errors" class="invalid-feedback">
                                <div *ngIf="f['password'].errors['required']">Password is required</div>
                                <div *ngIf="f['password'].errors['minlength']">
                                    Password must be at least 6 characters
                                </div>
                                <div *ngIf="f['password'].errors['maxlength']">
                                    Password must not exceed 40 characters
                                </div>
                            </div>
                        </div>
                        <p></p>
                    
                        <div class="form-group">
                            <label>Confirm Password</label>
                            <input type="password" 
                                formControlName="confirmPassword" 
                                class="form-control"
                                [ngClass]="{ 'is-invalid': submitted && f['confirmPassword'].errors }" />
                            <div *ngIf="submitted && f['confirmPassword'].errors" class="invalid-feedback">
                                <div *ngIf="f['confirmPassword'].errors['required']">
                                    Confirm Password is required
                                </div>
                                <div *ngIf="f['confirmPassword'].errors['matching']">
                                    Confirm Password does not match
                                </div>
                            </div>
                        </div>
                        <p></p>                       
                    
                        <div class="form-group">
                            <button type="submit" 
                                class="btn btn-success">
                                Register
                            </button>
                            &nbsp;&nbsp;
                            <button type="button" 
                                (click)="onReset()" 
                                class="btn btn-primary float-right">
                                Reset
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="register-form">
  
</div>

// reactapp-uadmin/src/components/Registration/Registration.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import StudentService from "../../services/student.service";

import { useNavigate } from "react-router";

import { getRoles } from "../../services/local.service";

const Registration = () => {
  let navigate = useNavigate();

  const [roles, setRoles] = useState([]);
  const [showStudents, setShowStudents] = useState(false);
  const [students, setStudents] = useState([]);

  const [modelErrors, setModelErrors] = useState([]);
  const [registerResponse, setRegisterResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currUser = AuthService.getCurrentUser();
    if (currUser !== null) navigate("/home");
    else setRoles(getRoles());
  }, []);

  // reset form
  // form reference
  const formRef = useRef(null);

  const setField = (field, value) => {
    if (field === "myRole" && value === "Student") {
      console.log("loading students!");
      setShowStudents(true);
      getStudentList();
    } else if (field === "myRole" && value === "Admin") {
      setShowStudents(false);
      setStudents([]);
    }

    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const getStudentList = () => {
    StudentService.allStudentsNotLinkedToApplicationUser()
      .then((response) => {
        console.log(response.data);
        setStudents(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  const findFormErrors = () => {
    const { myRole, studentId, username, email, password, confirmPassword } =
      form;
    const newErrors = {};

    if (!myRole || myRole === "") newErrors.myRole = "Role is Required!";

    if (myRole === "Student" && (!studentId || studentId === "")) {
      newErrors.studentId = "Student is Required!";
    }

    if (!username || username === "")
      newErrors.username = "User Name is Required!";

    var pattern = new RegExp(
      /^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i
    );
    if (!email || email === "") newErrors.email = "Email is Required!";
    else if (!pattern.test(email)) newErrors.email = "Invalid Email Address!";

    if (!password || password === "")
      newErrors.password = "Password is Required!";

    if (!confirmPassword || confirmPassword === "")
      newErrors.confirmPassword = "Confirm Password is Required!";

    if (password !== confirmPassword)
      newErrors.confirmPassword = "Passwords don't match!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var registerModel = {
        email: form.email,

        // check for ModelState @api
        // email: null,

        password: form.password,
        confirmPassword: form.confirmPassword,
        username: form.username,
        studentId: 0, // when my-role===Admin
      };

      // when my-role===Student
      if (form.myRole === "Student")
        registerModel.studentId = Number(form.studentId);

      console.log(registerModel);

      // api call
      AuthService.register(registerModel, form.myRole)
        .then((response) => {
          console.log(response.data);
          var registerResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          setRegisterResponse(registerResponse);

          if (response.data.responseCode === 0) {
            resetForm();
            setTimeout(() => {
              navigate("/login");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setRegisterResponse({});
          console.log(error.response.data.message);
          console.log(error.response);

          // 500
          if (error.response.status === 500) {
            var registerResponse = {
              responseCode: -1,
              responseMessage: error.response.data.message,
            };
            setRegisterResponse(registerResponse);
            console.log(registerResponse);
          }
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setRegisterResponse({});
    setModelErrors([]);
  };

  const renderOptionsForRole = () => {
    return roles.map((dt, i) => {
      return (
        <option value={dt.name} key={i} name={dt.name}>
          {dt.name}
        </option>
      );
    });
  };

  const renderOptionsForStudents = () => {
    return students.map((dt, i) => {
      return (
        <option
          value={dt.studentId}
          key={i}
          name={dt.firstName + ", " + dt.lastName}
        >
          {dt.firstName + ", " + dt.lastName}
        </option>
      );
    });
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-6 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>
                  <i className="bi bi-person-circle"></i> &nbsp; Registration
                </h3>
                <p></p>
                {registerResponse && registerResponse.responseCode === -1 ? (
                  <span className="registerError">
                    {registerResponse.responseMessage}
                  </span>
                ) : (
                  <span className="registerSuccess">
                    {registerResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-sm-6">
                      <Form.Group controlId="myRole">
                        <Form.Label>App Role</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.myRole}
                          onChange={(e) => {
                            setField("myRole", e.target.value);
                          }}
                        >
                          <option value="">Choose Role</option>
                          {renderOptionsForRole()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.myRole}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="studentId">
                        <Form.Label>Student</Form.Label>
                        <Form.Control
                          disabled={!showStudents}
                          as="select"
                          isInvalid={!!errors.studentId}
                          onChange={(e) => {
                            setField("studentId", e.target.value);
                          }}
                        >
                          <option value="">Choose Student</option>
                          {renderOptionsForStudents()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.studentId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="username">
                        <Form.Label>User Name</Form.Label>
                        <Form.Control
                          type="text"
                          isInvalid={!!errors.username}
                          onChange={(e) => setField("username", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.username}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-sm-6">
                      <Form.Group controlId="email">
                        <Form.Label>Email</Form.Label>
                        <Form.Control
                          type="text"
                          isInvalid={!!errors.email}
                          onChange={(e) => setField("email", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.email}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="password">
                        <Form.Label>Password</Form.Label>
                        <Form.Control
                          type="password"
                          isInvalid={!!errors.password}
                          onChange={(e) => setField("password", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.password}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="confirmPassword">
                        <Form.Label>Confirm Password</Form.Label>
                        <Form.Control
                          type="password"
                          isInvalid={!!errors.confirmPassword}
                          onChange={(e) =>
                            setField("confirmPassword", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.confirmPassword}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Register
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Registration;
