// ngApp/src/app/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CustomValidationService } from '../services/custom-validation.service';
import { UserService } from '../services/user.service';
import { Router } from '@angular/router';
import { LocalDataService } from '../services/local-data.service';
import { DataService } from '../services/data.service';
import Student from '../models/student';

@Component({
  selector: 'registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent implements OnInit {
  registerForm: FormGroup;
  submitted = false;

  students: Array<Student>;

  // controlls visibility of student select list
  showStudentList = false;

  registerModel = {
    UserName: '',
    FullName: '',
    Email: '',
    Password: '',
    StudentId: 0
  };

  constructor(
    private fb: FormBuilder,
    public customValidator: CustomValidationService,
    public userService: UserService,
    public router: Router,
    public localDataService: LocalDataService,
    public dataService: DataService
  ) { }

  // ok
  ngOnInit() {
    this.registerForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      username: ['', [Validators.required], this.customValidator.userNameValidator.bind(this.customValidator)],
      password: ['', Validators.compose([Validators.required, this.customValidator.patternValidator()])],
      confirmPassword: ['', [Validators.required]],
      MyRole: ['', [Validators.required]],
      studentId: ['', [Validators.required]]
    },
      {
        validator: this.customValidator.MatchPassword('password', 'confirmPassword'),
      }
    );

    
    if (this.userService.isLoggedIn) {
      // already logged in, so return to home page
      this.router.navigate(['/home']);
    }
    else {
      // not logged in yet
    }
    this.localDataService.setRegisterMessage('');
  }

  // ok
  get registerFormControl() {
    return this.registerForm.controls;
  }

  // ok
  // new user registration
  onSubmit(): void {

    // to ignore validation for studentId select list
    if(this.showStudentList==false){      
      this.registerForm.patchValue({
        studentId: 0
      });
    }

    this.submitted = true;

    if (this.registerForm.valid) {

      this.registerModel.FullName = this.registerForm.value["name"];
      this.registerModel.UserName = this.registerForm.value["username"];
      this.registerModel.Email = this.registerForm.value["email"];
      this.registerModel.Password = this.registerForm.value["password"];
      var MyRole = this.registerForm.value["MyRole"];
      this.registerModel.StudentId = Number(this.registerForm.value["studentId"]);
      
      this.userService.register(this.registerModel, MyRole).subscribe(
        res => {
          console.log(res);
          if (res.responseCode == 0) {
            // success
            this.localDataService.setRegisterMessage(res.responseMessage);

            this.resetRegistration();

            // redirect to login page
            setTimeout(() => {
              this.router.navigate(['/signin']);
            }, 5000); 
          }
          else {
            // fail
            this.localDataService.setRegisterMessage(res.responseMessage);
          }
        },
        error => {
          // fail
          // 500
          this.localDataService.setRegisterMessage(error.error.message);
        }
      );
    }
   
  }

  // ok
  resetRegistration() {
    this.registerForm.reset();
    this.submitted = false;
  }

  // ok
  public handleError = (controlName: string, errorName: string) => {
    return this.registerForm.controls[controlName].hasError(errorName);
  }

  // ok
  // when role is changed from select list
  changeRole(e) {
    // console.log(e.target.value);
    // if role is Student then load student select list
    // else return
    if(e.target.value=='Student'){
      // loading student select list
      console.log('loading student list...');
      this.showStudentList = true;
      this.loadStds();
    }
    else{
      this.showStudentList = false;
      return;
    }
  }
  // ok
  loadStds() {
    this.dataService.getStudentsNotLinkedToApplicationUser()
      .subscribe(
        data => {
          // console.log(data);
          this.students = data;
        },
        error => {
          console.log(error);
        });
  }
}


<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Registration Form</h3>
                    <h5 *ngIf="this.localDataService.getRegisterMessage()" style="font-size:medium; color: red;">
                        {{this.localDataService.getRegisterMessage()}}
                    </h5>
                </div>
                <div class="card-body">
                    <form class="form" [formGroup]="registerForm" (ngSubmit)="onSubmit()">
                       
                        <!-- role -->
                        <div class="form-group">
                            <label>Role : </label>
                            <select class="form-control" 
                                (change)="changeRole($event)" 
                                formControlName="MyRole">
                                <option disabled>Select Role</option>
                                <option value="">Choose Role</option>
                                <option value="Admin">Admin</option>
                                <option value="User">User</option>
                                <option value="Student">Student</option>
                            </select>
                            <span class="text-danger"
                                *ngIf="(registerFormControl.MyRole.touched || submitted) && handleError('MyRole', 'required')">
                                Role is required
                            </span>
                        </div>
                        <!-- student select list -->
                        <div *ngIf="showStudentList" class="form-group">
                            <label>Student : </label>
                            <select class="form-control" 
                                formControlName="studentId">
                                <option disabled>Choose Student</option>
                                <option value="">Choose Student</option>
                                <option 
                                    value={{s.studentId}} 
                                    *ngFor="let s of students">
                                        {{s.firstName}}, {{s.lastName}}
                                </option>
                            </select>
                            <span class="text-danger"
                                *ngIf="(registerFormControl.studentId.touched || submitted) && handleError('studentId', 'required')">
                                Student is required
                            </span>                          
                        </div>


                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" formControlName="name">
                            <span class="text-danger"
                                *ngIf="(registerFormControl.name.touched || submitted) && registerFormControl.name.errors?.required">
                                Name is required
                            </span>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" class="form-control" formControlName="email">
                            <span class="text-danger"
                                *ngIf="(registerFormControl.email.touched || submitted) && registerFormControl.email.errors?.required">
                                Email is required
                            </span>
                            <span class="text-danger"
                                *ngIf="registerFormControl.email.touched && registerFormControl.email.errors?.email">
                                Enter a valid email address
                            </span>
                        </div>
                        <div class="form-group">
                            <label>User Name</label>
                            <input type="text" class="form-control" formControlName="username">
                            <span class="text-danger"
                                *ngIf="(registerFormControl.username.touched || submitted) && registerFormControl.username.errors?.required">
                                User Name is required
                            </span>
                            <span class="text-danger"
                                *ngIf="registerFormControl.username.touched && registerFormControl.username.errors?.userNameNotAvailable">
                                User Name is not available
                            </span>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" formControlName="password">
                            <span class="text-danger"
                                *ngIf="(registerFormControl.password.touched || submitted) && registerFormControl.password.errors?.required">
                                Password is required
                            </span>
                            <span class="text-danger"
                                *ngIf="registerFormControl.password.touched && registerFormControl.password.errors?.invalidPassword">
                                Password should have minimum 8 characters, at least 1 uppercase letter, 1 lowercase
                                letter and 1 number
                            </span>
                        </div>
                        <div class="form-group">
                            <label>Confirm Password</label>
                            <input type="password" class="form-control" formControlName="confirmPassword">
                            <span class="text-danger"
                                *ngIf="(registerFormControl.confirmPassword.touched || submitted)&& registerFormControl.confirmPassword.errors?.required">
                                Confirm Password is required
                            </span>
                            <span class="text-danger"
                                *ngIf="registerFormControl.confirmPassword.touched && registerFormControl.confirmPassword.errors?.passwordMismatch">
                                Passwords doesnot match
                            </span>
                        </div>
                    
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6">
                                    <button type="submit" 
                                        class="btn btn-success">Register
                                    </button>
                                </div>   
                                <div class="col-sm-6">
                                    <button type="button" 
                                        (click)="resetRegistration()" 
                                        class="btn btn-primary">
                                        Cancel
                                    </button>
                                </div>
                            </div>                         
                        </div>                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

// reactapp-uadmin/src/components/Registration/Registration.jsx
import React, { useEffect, useState, useRef } from "react";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import StudentService from "../../services/student.service";

import { useNavigate } from "react-router";

import { getRoles } from "../../services/local.service";

const Registration = () => {
  let navigate = useNavigate();

  const [roles, setRoles] = useState([]);
  const [showStudents, setShowStudents] = useState(false);
  const [students, setStudents] = useState([]);

  const [modelErrors, setModelErrors] = useState([]);
  const [registerResponse, setRegisterResponse] = useState({});

  // form
  const [form, setForm] = useState({});
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currUser = AuthService.getCurrentUser();
    if (currUser !== null) navigate("/home");
    else setRoles(getRoles());
  }, []);

  // reset form
  // form reference
  const formRef = useRef(null);

  const setField = (field, value) => {
    if (field === "myRole" && value === "Student") {
      console.log("loading students!");
      setShowStudents(true);
      getStudentList();
    } else if (field === "myRole" && value === "Admin") {
      setShowStudents(false);
      setStudents([]);
    }

    setForm({
      ...form,
      [field]: value,
    });

    // Check and see if errors exist, and remove them from the error object:
    if (!!errors[field])
      setErrors({
        ...errors,
        [field]: null,
      });
  };

  const getStudentList = () => {
    StudentService.allStudentsNotLinkedToApplicationUser()
      .then((response) => {
        console.log(response.data);
        setStudents(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  const findFormErrors = () => {
    const { myRole, studentId, username, email, password, confirmPassword } =
      form;
    const newErrors = {};

    if (!myRole || myRole === "") newErrors.myRole = "Role is Required!";

    if (myRole === "Student" && (!studentId || studentId === "")) {
      newErrors.studentId = "Student is Required!";
    }

    if (!username || username === "")
      newErrors.username = "User Name is Required!";

    var pattern = new RegExp(
      /^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i
    );
    if (!email || email === "") newErrors.email = "Email is Required!";
    else if (!pattern.test(email)) newErrors.email = "Invalid Email Address!";

    if (!password || password === "")
      newErrors.password = "Password is Required!";

    if (!confirmPassword || confirmPassword === "")
      newErrors.confirmPassword = "Confirm Password is Required!";

    if (password !== confirmPassword)
      newErrors.confirmPassword = "Passwords don't match!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var registerModel = {
        email: form.email,

        // check for ModelState @api
        // email: null,

        password: form.password,
        confirmPassword: form.confirmPassword,
        username: form.username,
        studentId: 0, // when my-role===Admin
      };

      // when my-role===Student
      if (form.myRole === "Student")
        registerModel.studentId = Number(form.studentId);

      console.log(registerModel);

      // api call
      AuthService.register(registerModel, form.myRole)
        .then((response) => {
          console.log(response.data);
          var registerResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          setRegisterResponse(registerResponse);

          if (response.data.responseCode === 0) {
            resetForm();
            setTimeout(() => {
              navigate("/login");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setRegisterResponse({});
          console.log(error.response.data.message);
          console.log(error.response);

          // 500
          if (error.response.status === 500) {
            var registerResponse = {
              responseCode: -1,
              responseMessage: error.response.data.message,
            };
            setRegisterResponse(registerResponse);
            console.log(registerResponse);
          }
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setForm({});
    setRegisterResponse({});
    setModelErrors([]);
  };

  const renderOptionsForRole = () => {
    return roles.map((dt, i) => {
      return (
        <option value={dt.name} key={i} name={dt.name}>
          {dt.name}
        </option>
      );
    });
  };

  const renderOptionsForStudents = () => {
    return students.map((dt, i) => {
      return (
        <option
          value={dt.studentId}
          key={i}
          name={dt.firstName + ", " + dt.lastName}
        >
          {dt.firstName + ", " + dt.lastName}
        </option>
      );
    });
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-6 mx-auto">
            <div className="card">
              <div className="card-header">
                <h3>
                  <i className="bi bi-person-circle"></i> &nbsp; Registration
                </h3>
                <p></p>
                {registerResponse && registerResponse.responseCode === -1 ? (
                  <span className="registerError">
                    {registerResponse.responseMessage}
                  </span>
                ) : (
                  <span className="registerSuccess">
                    {registerResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-sm-6">
                      <Form.Group controlId="myRole">
                        <Form.Label>App Role</Form.Label>
                        <Form.Control
                          as="select"
                          isInvalid={!!errors.myRole}
                          onChange={(e) => {
                            setField("myRole", e.target.value);
                          }}
                        >
                          <option value="">Choose Role</option>
                          {renderOptionsForRole()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.myRole}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="studentId">
                        <Form.Label>Student</Form.Label>
                        <Form.Control
                          disabled={!showStudents}
                          as="select"
                          isInvalid={!!errors.studentId}
                          onChange={(e) => {
                            setField("studentId", e.target.value);
                          }}
                        >
                          <option value="">Choose Student</option>
                          {renderOptionsForStudents()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.studentId}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="username">
                        <Form.Label>User Name</Form.Label>
                        <Form.Control
                          type="text"
                          isInvalid={!!errors.username}
                          onChange={(e) => setField("username", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.username}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-sm-6">
                      <Form.Group controlId="email">
                        <Form.Label>Email</Form.Label>
                        <Form.Control
                          type="text"
                          isInvalid={!!errors.email}
                          onChange={(e) => setField("email", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.email}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="password">
                        <Form.Label>Password</Form.Label>
                        <Form.Control
                          type="password"
                          isInvalid={!!errors.password}
                          onChange={(e) => setField("password", e.target.value)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.password}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="confirmPassword">
                        <Form.Label>Confirm Password</Form.Label>
                        <Form.Control
                          type="password"
                          isInvalid={!!errors.confirmPassword}
                          onChange={(e) =>
                            setField("confirmPassword", e.target.value)
                          }
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.confirmPassword}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Register
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Registration;
