// reactapp-uadmin/src/components/Student_Edit/Student_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import StudentService from "../../services/student.service";

import { useNavigate } from "react-router";

import Moment from "moment";

const Student_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();
  const [genders, setGenders] = useState([]);

  const [modelErrors, setModelErrors] = useState([]);
  const [studentEditResponse, setStudentEditResponse] = useState({});

  // form
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [email, setEmail] = useState("");
  const [gender, setGender] = useState("");
  const [homeAddress, setHomeAddress] = useState("");
  const [homePostalCode, setHomePostalCode] = useState("");
  const [mailAddress, setMailAddress] = useState("");
  const [mailPostalCode, setMailPostalCode] = useState("");

  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      setGenders(["Male", "Female", "Other"]);
      getStudent(id);
    }
  }, []);

  const getStudent = (id) => {
    console.log("Editing student : ", id);
    if (checkForNumbersOnly(id)) {
      StudentService.getStudent(id)
        .then((response) => {
          if (response.data === "") {
            // data not found on server!
            var studentEditResponse = {
              responseCode: -1,
              responseMessage: "Student Not Found!",
            };

            setStudentEditResponse(studentEditResponse);
          } else {
            console.log(response.data);

            setFirstName(response.data.firstName);
            setLastName(response.data.lastName);
            response.data.phoneNumber !== null
              ? setPhoneNumber(response.data.phoneNumber)
              : setPhoneNumber("");
            setEmail(response.data.email);
            setGender(convertGenderForDisplay(response.data.gender));
            response.data.homeAddress !== null
              ? setHomeAddress(response.data.homeAddress)
              : setHomeAddress("");
            response.data.homePostalCode !== null
              ? setHomePostalCode(response.data.homePostalCode)
              : setHomePostalCode("");
            response.data.mailAddress !== null
              ? setMailAddress(response.data.mailAddress)
              : setMailAddress("");
            response.data.mailPostalCode !== null
              ? setMailPostalCode(response.data.mailPostalCode)
              : setMailPostalCode("");
          }
        })
        .catch((e) => {
          console.log(e);
        });
    } else navigate("/student");
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const handleFirstName = (event) => {
    setFirstName(event.target.value);
    if (!errors[firstName])
      setErrors({
        ...errors,
        firstName: "",
      });
  };
  const handleLastName = (event) => {
    setLastName(event.target.value);
    if (!errors[lastName])
      setErrors({
        ...errors,
        lastName: "",
      });
  };
  const handlePhoneNumber = (event) => {
    setPhoneNumber(event.target.value);
    if (!errors[phoneNumber])
      setErrors({
        ...errors,
        phoneNumber: "",
      });
  };
  const handleEmail = (event) => {
    setEmail(event.target.value);
    if (!errors[email])
      setErrors({
        ...errors,
        email: "",
      });
  };
  const handleGender = (event) => {
    setGender(event.target.value);
    if (!errors[gender])
      setErrors({
        ...errors,
        gender: "",
      });
  };
  const handleHomeAddress = (event) => {
    setHomeAddress(event.target.value);
    if (!errors[homeAddress])
      setErrors({
        ...errors,
        homeAddress: "",
      });
  };
  const handleHomePostalCode = (event) => {
    setHomePostalCode(event.target.value);
    if (!errors[homePostalCode])
      setErrors({
        ...errors,
        homePostalCode: "",
      });
  };
  const handleMailAddress = (event) => {
    setMailAddress(event.target.value);
    if (!errors[mailAddress])
      setErrors({
        ...errors,
        mailAddress: "",
      });
  };
  const handleMailPostalCode = (event) => {
    setMailPostalCode(event.target.value);
    if (!errors[mailPostalCode])
      setErrors({
        ...errors,
        mailPostalCode: "",
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const checkForPhoneNumber = (newVal) => {
    // const re = /^(\([0-9]{3}\)|[0-9]{3}-)[0-9]{3}-[0-9]{4}$/;
    const re = /^(()?\d{3}())?(-|\s)?\d{3}(-|\s)?\d{4}$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const checkForEmail = (newVal) => {
    const re = /^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[A-Za-z]+$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const newErrors = {};

    if (!firstName || firstName === "")
      newErrors.firstName = "First Name is Required!";
    if (!lastName || lastName === "")
      newErrors.lastName = "Last Name is Required!";

    if (!(!phoneNumber || phoneNumber === "")) {
      if (!checkForPhoneNumber(phoneNumber))
        newErrors.phoneNumber = "Invalid Phone Number!";
    }

    if (!email || email === "") newErrors.email = "Email is Required!";
    if (!(!email || email === "")) {
      if (!checkForEmail(email)) newErrors.email = "Invalid Email!";
    }

    if (!gender || gender === "") newErrors.gender = "Gender is Required!";

    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const convertGender = (gender) => {
    if (gender === "Male") return 0;
    else if (gender === "Female") return 1;
    else return 2;
  };

  const convertGenderForDisplay = (genderCode) => {
    if (genderCode === 0) return "Male";
    else if (genderCode === 1) return "Female";
    else return "Other";
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var studentModel = {
        firstName: firstName,
        lastName: lastName,
        phoneNumber: phoneNumber,
        email: email,
        gender: convertGender(gender),
        homeAddress:
          homeAddress !== "" || homeAddress !== undefined ? homeAddress : "",
        homePostalCode:
          homePostalCode !== "" || homePostalCode !== undefined
            ? homePostalCode
            : "",
        mailAddress:
          mailAddress !== "" || mailAddress !== undefined ? mailAddress : "",
        mailPostalCode:
          mailPostalCode !== "" || mailPostalCode !== undefined
            ? mailPostalCode
            : "",
        studentId: Number(id),
      };

      console.log(studentModel);

      // api call
      StudentService.editStudent(studentModel)
        .then((response) => {
          console.log(response.data);
          setModelErrors([]);
          setStudentEditResponse({});
          var studentEditResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          resetForm();
          setStudentEditResponse(studentEditResponse);
          if (response.data.responseCode === 0) {
            setTimeout(() => {
              navigate("/student");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setStudentEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          } else {
            console.log(error);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setFirstName("");
    setLastName("");
    setPhoneNumber("");
    setEmail("");
    setGender("");
    setHomeAddress("");
    setHomePostalCode("");
    setMailAddress("");
    setMailPostalCode("");
    setStudentEditResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  const renderOptionsForGenders = () => {
    return genders.map((dt, i) => {
      return (
        <option value={dt} key={i} name={dt}>
          {dt}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-8 mx-auto">
            <div className="card">
              <div className="card-header header">
                <h3>Edit Student # {id}</h3>
                <p></p>{" "}
                {studentEditResponse &&
                studentEditResponse.responseCode === -1 ? (
                  <span className="studentEditError">
                    {studentEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="studentEditSuccess">
                    {studentEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-5 mx-auto">
                      <Form.Group controlId="firstName">
                        <Form.Label>First Name</Form.Label>
                        <Form.Control
                          value={firstName}
                          type="text"
                          isInvalid={!!errors.firstName}
                          onChange={(e) => handleFirstName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.firstName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="lastName">
                        <Form.Label>Last Name</Form.Label>
                        <Form.Control
                          type="text"
                          value={lastName}
                          isInvalid={!!errors.lastName}
                          onChange={(e) => handleLastName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.lastName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="phoneNumber">
                        <Form.Label>Phone</Form.Label>
                        <Form.Control
                          type="text"
                          value={phoneNumber}
                          isInvalid={!!errors.phoneNumber}
                          onChange={(e) => handlePhoneNumber(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.phoneNumber}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="email">
                        <Form.Label>Email</Form.Label>
                        <Form.Control
                          type="text"
                          value={email}
                          isInvalid={!!errors.email}
                          onChange={(e) => handleEmail(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.email}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-md-5 mx-auto">
                      <Form.Group controlId="gender">
                        <Form.Label>Gender</Form.Label>
                        <Form.Control
                          as="select"
                          value={gender}
                          isInvalid={!!errors.gender}
                          onChange={(e) => handleGender(e)}
                        >
                          <option value="">Select Gender</option>
                          {renderOptionsForGenders()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.gender}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="homeAddress">
                        <Form.Label>Home Address</Form.Label>
                        <Form.Control
                          value={homeAddress}
                          type="text"
                          isInvalid={!!errors.homeAddress}
                          onChange={(e) => handleHomeAddress(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.homeAddress}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="homePostalCode">
                        <Form.Label>Home Postal Code</Form.Label>
                        <Form.Control
                          value={homePostalCode}
                          type="text"
                          isInvalid={!!errors.homePostalCode}
                          onChange={(e) => handleHomePostalCode(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.homePostalCode}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>{" "}
                      <Form.Group controlId="mailAddress">
                        <Form.Label>Mail Address</Form.Label>
                        <Form.Control
                          value={mailAddress}
                          type="text"
                          isInvalid={!!errors.mailAddress}
                          onChange={(e) => handleMailAddress(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.mailAddress}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="mailAPostalCode">
                        <Form.Label>Mail Postal Code</Form.Label>
                        <Form.Control
                          value={mailPostalCode}
                          type="text"
                          isInvalid={!!errors.mailPostalCode}
                          onChange={(e) => handleMailPostalCode(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.mailPostalCode}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                    }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Student
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Student_Edit;

// NgApp/src/app/student-edit/student-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import Student from '../models/student';

@Component({
  selector: 'app-student-edit',
  templateUrl: './student-edit.component.html',
  styleUrls: ['./student-edit.component.css']
})
export class StudentEditComponent implements OnInit {
  
  // can't change
  studentId: string;

  stdForm: FormGroup;
  submitted = false;
  studentModel = new Student();

  editStdPanel = true;
  genderCollection: any = ['Male', 'Female', 'Other'];

  responseColor = '';
  errors: string[];
  apiResponse = ''; 

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }

  // ok
  ngOnInit(): void {
    this.stdForm = this.fb.group({
      FirstName: ['', Validators.required],
      LastName: ['', Validators.required],
      Email: ['', [Validators.required, Validators.email]],
      Gender: ['', Validators.required],
      PhoneNumber: ['', [Validators.required, Validators.pattern("^(\([0-9]{3}\)|[0-9]{3}-)[0-9]{3}-[0-9]{4}$")]],
      HomeAddress: [''],
      MailAddress: [''],
      HomePostalCode: ['', [Validators.pattern("[A-Za-z][0-9][A-Za-z] [0-9][A-Za-z][0-9]")]],
      MailPostalCode: ['', [Validators.pattern("[A-Za-z][0-9][A-Za-z] [0-9][A-Za-z][0-9]")]]
    });

    this.studentId = this.route.snapshot.paramMap.get('id');

    if (isNaN(+this.studentId)){
      console.log('Not a Number!');
      this.router.navigate(['/student']);
    }
    else{
      // do api call to retrieve latest student information 
      this.dataService.getStd(Number(this.studentId))
        .subscribe(
          data => {
            if (data == null) {
              console.log('student not found!');
              this.editStdPanel=false;
              // fail
              // display error message
              this.apiResponse = 'Student Not Found!';
              this.responseColor = 'red';
            }
            else {
              this.apiResponse = '';
              this.responseColor = 'green';
              this.editStdPanel = true;

              console.log(data);
              // popup form data with incoming api data call          
              this.stdForm.setValue({
                FirstName: data.firstName,
                LastName: data.lastName,
                Email: data.email,
                Gender: this.convertGenderToFormControl(data.gender),
                PhoneNumber: data.phoneNumber,
                HomeAddress: data.homeAddress,
                MailAddress: data.mailAddress,
                HomePostalCode: data.homePostalCode,
                MailPostalCode: data.mailPostalCode
              });
            }
          },
          error => {
            console.log(error);
          });
    }
  }

  // ok
  get stdFormControl() {
    return this.stdForm.controls;
  }

  // ok
  convertGender(gender) {
    if (gender == 'Male')
      return 0;
    else if (gender == 'Female')
      return 1;
    else
      return 2;
  }

  // ok
  /* Gender error handling */
  public handleError = (controlName: string, errorName: string) => {
    return this.stdForm.controls[controlName].hasError(errorName);
  }

  // this will convert gender db column to gender selectlist value
  convertGenderToFormControl(gender) {
    if (gender == 0)
      return 'Male';
    else if (gender == 1)
      return 'Female';
    else
      return 'Other';
  }

  // ok
  onSubmit(): void {

    this.responseColor = '';
    this.errors = []; 
    this.apiResponse = '';


    this.submitted = true;
    if (this.stdForm.valid) {
      this.studentModel.studentId = Number(this.studentId);

      this.studentModel.firstName = this.stdForm.value["FirstName"];
      this.studentModel.lastName = this.stdForm.value["LastName"];
      this.studentModel.phoneNumber = this.stdForm.value["PhoneNumber"];
      this.studentModel.email = this.stdForm.value["Email"];
      this.studentModel.gender = this.convertGender(this.stdForm.value["Gender"]);
      this.studentModel.homeAddress = this.stdForm.value["HomeAddress"];
      this.studentModel.homePostalCode = this.stdForm.value["HomePostalCode"];
      this.studentModel.mailAddress = this.stdForm.value["MailAddress"];
      this.studentModel.mailPostalCode = this.stdForm.value["MailPostalCode"];

      this.dataService.editStd(this.studentModel)
        .subscribe(
          response => {
            if (response.responseCode == 0) {
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.editStdPanel = false;

              // redirect to student component
              setTimeout(() => {
                this.router.navigate(['/student']);
              }, 3000);
            }
            else {
              // fail
              // display error message
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
              this.editStdPanel = true;
            }
          },
          error => {
            this.responseColor = 'red';
            // 400
            // ModelState @api
            if (error.status === 400) {   
              this.errors = this.localDataService.display400andEx(error, 'Registration');      
            }
            // 500
            else{
              console.log(error);
            }     
            this.editStdPanel = true;
          }
        );
    }
  }

  // ok
  resetStd() {
    this.apiResponse = '';
    this.responseColor = '';
    this.stdForm.reset();
    this.submitted = false;

    this.router.navigate(['/student']);
  }

  // ok
  onPhoneNumberChange(event) {
    var phoneNumber = event.target.value;
    
    if (phoneNumber.length == 3) {
      this.stdForm.patchValue({
        PhoneNumber: phoneNumber + '-'
      });
    }
    else if (phoneNumber.length == 7) {
      this.stdForm.patchValue({
        PhoneNumber: phoneNumber + '-'
      });
    }
    else {
      this.stdForm.patchValue({
        PhoneNumber: phoneNumber
      });
    }
  }
}

<div class="container">
    <div class="col-md-10 mx-auto">
        <div class="card" style="background-color:lightgoldenrodyellow;">
            <div class="card-header">
                <h3>
                    <div>
                        #{{studentId}}) Student - Edit
                    </div>
                    <hr />
                    <h5 *ngIf="apiResponse">
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                        <hr />
                    </h5>
                    <h5 *ngIf="errors?.length > 0">
                        <p></p>
                        <ul [style.color]="responseColor">
                            <li *ngFor="let error of errors">
                                {{ error }}
                            </li>
                        </ul>
                    </h5>
                </h3>
            </div>
            <div class="card-body" *ngIf="editStdPanel">
                <form class="form-std" [formGroup]="stdForm" (ngSubmit)="onSubmit()">
                    <div class="row">
                        <div class="col-md-6 mx-auto">
                            <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control" formControlName="FirstName">
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(stdFormControl.FirstName.touched || submitted) && stdFormControl.FirstName.errors?.required">
                                    First Name is required
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" formControlName="LastName">
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(stdFormControl.LastName.touched || submitted) && stdFormControl.LastName.errors?.required">
                                    Last Name is required
                                </div>
                            </div>
                            <p></p>
                            <!-- PhoneNumber -->
                            <div class="form-group">
                                <label>Phone </label>
                                <input type="text" 
                                    (input)="onPhoneNumberChange($event)"
                                    class="form-control" 
                                    formControlName="PhoneNumber">
                                <div *ngIf="(stdFormControl.PhoneNumber.touched || submitted) && stdFormControl.PhoneNumber.invalid"
                                    class="alert alert-danger mt-2">
                                    <span *ngIf="stdFormControl.PhoneNumber.errors.required">Phone Number is
                                        required</span>
                                    <span *ngIf="stdFormControl.PhoneNumber.errors.pattern">Invalid Phone Number
                                        Format</span>
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="text" class="form-control" formControlName="Email">
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(stdFormControl.Email.touched || submitted) && stdFormControl.Email.errors?.required">
                                    Email is required
                                </div>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(stdFormControl.Email.touched || submitted) && stdFormControl.Email.errors?.email">
                                    Invalid Email address
                                </div>
                            </div>
                            <p></p>
                            <div class="form-group">
                                <label>Gender : </label>
                                <select class="form-control" formControlName="Gender">
                                    <option disabled>Select Gender</option>
                                    <option value="">Choose Gender</option>
                                    <option *ngFor="let g of genderCollection">
                                        {{g}}
                                    </option>
                                </select>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(stdFormControl.Gender.touched || submitted) && handleError('Gender', 'required')">
                                    Gender is required
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mx-auto">
                            <!-- home address -->
                            <div class="form-group">
                                <label>Home Address</label>
                                <input type="text" class="form-control" formControlName="HomeAddress">
                            </div>
                            <p></p>
                            <!-- home postal code -->
                            <div class="form-group">
                                <label>Home Postal Code</label>
                                <input type="text" class="form-control" formControlName="HomePostalCode">
                                <div *ngIf="(stdFormControl.HomePostalCode.touched || submitted) && stdFormControl.HomePostalCode.invalid"
                                    class="alert alert-danger mt-2">
                                    <span *ngIf="stdFormControl.HomePostalCode.errors.pattern">Invalid Home-PostalCode
                                        Format</span>
                                </div>
                            </div>
                            <p></p>
                            <!-- mail address -->
                            <div class="form-group">
                                <label>Mail Address</label>
                                <input type="text" class="form-control" formControlName="MailAddress">
                            </div>
                            <p></p>
                            <!-- mail postal code -->
                            <div class="form-group">
                                <label>Mail Postal Code</label>
                                <input type="text" class="form-control" formControlName="MailPostalCode">
                                <div *ngIf="(stdFormControl.MailPostalCode.touched || submitted) && stdFormControl.MailPostalCode.invalid"
                                    class="alert alert-danger mt-2">
                                    <span *ngIf="stdFormControl.MailPostalCode.errors.pattern">Invalid Mail-PostalCode
                                        Format</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr />
                    <div class="row">
                        <div class="col-md-12 mx-auto">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-2 sx-auto">
                                        <button type="submit" class="btn btn-success">
                                            Edit Student
                                        </button>
                                    </div>
                                    <div class="col-sm-2 sx-auto">
                                        <button type="button" (click)="resetStd()" class="btn btn-primary">
                                            Cancel
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
