// reactapp-uadmin/src/components/Faculty_Edit/Faculty_Edit.jsx
import React, { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import "./style.css";

import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

import AuthService from "../../services/auth.service";
import DepartmentService from "../../services/department.service";
import FacultyService from "../../services/faculty.service";

import { useNavigate } from "react-router";

import Moment from "moment";

const Faculty_Edit = () => {
  let navigate = useNavigate();

  let { id } = useParams();
  const [genders, setGenders] = useState([]);
  const [depts, setDepts] = useState([]);

  const [modelErrors, setModelErrors] = useState([]);
  const [facEditResponse, setFacEditResponse] = useState({});

  // form
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [email, setEmail] = useState("");
  const [gender, setGender] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const [errors, setErrors] = useState({});

  useEffect(() => {
    var currRole = AuthService.getCurrentUserRole();

    if (currRole === null || (currRole !== null && currRole !== "Admin"))
      navigate("/un-auth");
    else {
      setGenders(["Male", "Female", "Other"]);
      getAllDepartments();
      getFaculty(id);
    }
  }, []);

  const getAllDepartments = () => {
    DepartmentService.allDepartments()
      .then((response) => {
        console.log(response.data);
        setDepts(response.data);
      })
      .catch((e) => {
        console.log(e);
        if (e.response.status === 401) {
          console.log("Token Not Found!");
          AuthService.logout();
          navigate("/login");
        }
      });
  };

  const getFaculty = (id) => {
    console.log("Editing faculty : ", id);
    if (checkForNumbersOnly(id)) {
      FacultyService.getFaculty(id)
        .then((response) => {
          if (response.data === "") {
            // data not found on server!
            var facEditResponse = {
              responseCode: -1,
              responseMessage: "Faculty Not Found!",
            };

            setFacEditResponse(facEditResponse);
          } else {
            console.log(response.data);

            setFirstName(response.data.firstName);
            setLastName(response.data.lastName);
            setPhoneNumber(response.data.phoneNumber);
            setEmail(response.data.email);
            setGender(convertGenderForDisplay(response.data.gender));
            setDepartmentId(response.data.departmentId);
          }
        })
        .catch((e) => {
          console.log(e);
        });
    } else navigate("/faculty");
  };

  // reset form
  // form reference
  const formRef = useRef(null);

  const handleFirstName = (event) => {
    setFirstName(event.target.value);
    if (!errors[firstName])
      setErrors({
        ...errors,
        firstName: "",
      });
  };
  const handleLastName = (event) => {
    setLastName(event.target.value);
    if (!errors[lastName])
      setErrors({
        ...errors,
        lastName: "",
      });
  };
  const handlePhoneNumber = (event) => {
    setPhoneNumber(event.target.value);
    if (!errors[phoneNumber])
      setErrors({
        ...errors,
        phoneNumber: "",
      });
  };
  const handleEmail = (event) => {
    setEmail(event.target.value);
    if (!errors[email])
      setErrors({
        ...errors,
        email: "",
      });
  };
  const handleGender = (event) => {
    setGender(event.target.value);
    if (!errors[gender])
      setErrors({
        ...errors,
        gender: "",
      });
  };
  const handleDepartmentId = (event) => {
    setDepartmentId(event.target.value);
    if (!errors[departmentId])
      setErrors({
        ...errors,
        departmentId: "",
      });
  };

  const checkForNumbersOnly = (newVal) => {
    const re = /^\d*\.?\d*$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const checkForPhoneNumber = (newVal) => {
    // const re = /^(\([0-9]{3}\)|[0-9]{3}-)[0-9]{3}-[0-9]{4}$/;
    const re = /^(()?\d{3}())?(-|\s)?\d{3}(-|\s)?\d{4}$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const checkForEmail = (newVal) => {
    const re = /^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[A-Za-z]+$/;
    if (re.test(newVal)) return true;
    else return false;
  };

  const findFormErrors = () => {
    const newErrors = {};

    if (!firstName || firstName === "")
      newErrors.firstName = "First Name is Required!";
    if (!lastName || lastName === "")
      newErrors.lastName = "Last Name is Required!";

    if (!(!phoneNumber || phoneNumber === "")) {
      if (!checkForPhoneNumber(phoneNumber))
        newErrors.phoneNumber = "Invalid Phone Number!";
    }

    if (!email || email === "") newErrors.email = "Email is Required!";
    if (!(!email || email === "")) {
      if (!checkForEmail(email)) newErrors.email = "Invalid Email!";
    }

    if (!gender || gender === "") newErrors.gender = "Gender is Required!";

    if (!departmentId || departmentId === "")
      newErrors.departmentId = "Department is Required!";
    return newErrors;
  };

  const handleModelState = (error) => {
    var errors = [];
    if (error.response.status === 400) {
      // console.log(error.response.data);

      for (let prop in error.response.data.errors) {
        if (error.response.data.errors[prop].length > 1) {
          for (let error_ in error.response.data.errors[prop]) {
            errors.push(error.response.data.errors[prop][error_]);
          }
        } else {
          errors.push(error.response.data.errors[prop]);
        }
      }
    } else {
      console.log(error);
    }
    return errors;
  };

  const convertGender = (gender) => {
    if (gender === "Male") return 0;
    else if (gender === "Female") return 1;
    else return 2;
  };

  const convertGenderForDisplay = (genderCode) => {
    if (genderCode === 0) return "Male";
    else if (genderCode === 1) return "Female";
    else return "Other";
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const newErrors = findFormErrors();

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
    } else {
      var facModel = {
        firstName: firstName,
        lastName: lastName,
        phoneNumber: phoneNumber,
        email: email,
        gender: convertGender(gender),
        departmentId: Number(departmentId),
        facultyId: Number(id),
      };

      console.log(facModel);

      // api call
      FacultyService.editFaculty(facModel)
        .then((response) => {
          console.log(response.data);
          setModelErrors([]);
          setFacEditResponse({});
          var facEditResponse = {
            responseCode: response.data.responseCode,
            responseMessage: response.data.responseMessage,
          };

          resetForm();
          setFacEditResponse(facEditResponse);
          if (response.data.responseCode === 0) {
            setTimeout(() => {
              navigate("/faculty");
            }, 3000);
          }
        })
        .catch((error) => {
          setModelErrors([]);
          setFacEditResponse({});
          // 400
          // ModelState
          if (error.response.status === 400) {
            console.log("400 !");
            var modelErrors = handleModelState(error);
            setModelErrors(modelErrors);
          } else {
            console.log(error);
          }
        });
    }
  };

  const resetForm = (e) => {
    formRef.current.reset();
    setErrors({});
    setFirstName("");
    setLastName("");
    setPhoneNumber("");
    setEmail("");
    setGender("");
    setDepartmentId("");
    setFacEditResponse({});
    setModelErrors([]);
  };

  let modelErrorList =
    modelErrors.length > 0 &&
    modelErrors.map((item, i) => {
      return (
        <ul key={i} value={item}>
          <li style={{ marginTop: -20 }}>{item}</li>
        </ul>
      );
    }, this);

  const renderOptionsForGenders = () => {
    return genders.map((dt, i) => {
      return (
        <option value={dt} key={i} name={dt}>
          {dt}
        </option>
      );
    });
  };

  const renderOptionsForDepartments = () => {
    return depts.map((dt, i) => {
      return (
        <option value={dt.departmentId} key={i} name={dt.departmentName}>
          {dt.departmentName}
        </option>
      );
    });
  };

  return (
    <div className="mainContainer">
      <div className="container">
        <div className="row">
          <div className="col-md-8 mx-auto">
            <div className="card">
              <div className="card-header header">
                <h3>Edit Faculty # {id}</h3>
                <p></p>{" "}
                {facEditResponse && facEditResponse.responseCode === -1 ? (
                  <span className="facEditError">
                    {facEditResponse.responseMessage}
                  </span>
                ) : (
                  <span className="facEditSuccess">
                    {facEditResponse.responseMessage}
                  </span>
                )}
                {modelErrors.length > 0 ? (
                  <div className="modelError">{modelErrorList}</div>
                ) : (
                  <span></span>
                )}
              </div>
              <div className="card-body">
                <Form ref={formRef}>
                  <div className="row">
                    <div className="col-md-5 mx-auto">
                      <Form.Group controlId="firstName">
                        <Form.Label>First Name</Form.Label>
                        <Form.Control
                          value={firstName}
                          type="text"
                          isInvalid={!!errors.firstName}
                          onChange={(e) => handleFirstName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.firstName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="lastName">
                        <Form.Label>Last Name</Form.Label>
                        <Form.Control
                          type="text"
                          value={lastName}
                          isInvalid={!!errors.lastName}
                          onChange={(e) => handleLastName(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.lastName}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="phoneNumber">
                        <Form.Label>Phone</Form.Label>
                        <Form.Control
                          type="text"
                          value={phoneNumber}
                          isInvalid={!!errors.phoneNumber}
                          onChange={(e) => handlePhoneNumber(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.phoneNumber}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                    <div className="col-md-5 mx-auto">
                      <Form.Group controlId="email">
                        <Form.Label>Email</Form.Label>
                        <Form.Control
                          type="text"
                          value={email}
                          isInvalid={!!errors.email}
                          onChange={(e) => handleEmail(e)}
                        />
                        <Form.Control.Feedback type="invalid">
                          {errors.email}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="gender">
                        <Form.Label>Gender</Form.Label>
                        <Form.Control
                          as="select"
                          value={gender}
                          isInvalid={!!errors.gender}
                          onChange={(e) => handleGender(e)}
                        >
                          <option value="">Select Gender</option>
                          {renderOptionsForGenders()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.gender}
                        </Form.Control.Feedback>
                      </Form.Group>
                      <p></p>
                      <Form.Group controlId="departmentId">
                        <Form.Label>Department</Form.Label>
                        <Form.Control
                          as="select"
                          value={departmentId}
                          isInvalid={!!errors.departmentId}
                          onChange={(e) => handleDepartmentId(e)}
                        >
                          <option value="">Select Department</option>
                          {renderOptionsForDepartments()}
                        </Form.Control>
                        <Form.Control.Feedback type="invalid">
                          {errors.departmentId}
                        </Form.Control.Feedback>
                      </Form.Group>
                    </div>
                  </div>

                  <p></p>
                  <div
                    style={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <Button
                      className="btn btn-success"
                      type="button"
                      onClick={(e) => handleSubmit(e)}
                    >
                      Edit Faculty
                    </Button>
                    <Button
                      className="btn btn-primary"
                      type="button"
                      onClick={(e) => resetForm(e)}
                    >
                      Reset
                    </Button>
                  </div>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Faculty_Edit;

// ngApp/src/app/faculty-edit/faculty-edit.component.ts
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { DataService } from '../services/data.service';
import Department from '../models/department';
import { Observable } from 'rxjs';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LocalDataService } from '../services/local-data.service';
import Faculty from '../models/faculty';

@Component({
  selector: 'app-faculty-edit',
  templateUrl: './faculty-edit.component.html',
  styleUrls: ['./faculty-edit.component.css']
})
export class FacultyEditComponent implements OnInit {

  // ui can change departmentId for a particular facultyId @Faculty db table
  // so run code @Course db table to change departmentId column value for
  // a respective facultyId
  // set DepartmentId = new value
  // where FacultyId = facultyId of currently changed faculty's facultyId

  // can't change
  facultyId: string;

  departments: Array<Department>;
  genderCollection: any = ['Male', 'Female', 'Other'];
  facForm: FormGroup;
  submitted = false;
  facultyModel = new Faculty();
   
  editFacPanel = true;

  apiResponse = '';
  responseColor = '';

  constructor(public localDataService: LocalDataService, private fb: FormBuilder, public dataService: DataService, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.facForm = this.fb.group({
      FirstName: ['', Validators.required],
      LastName: ['', Validators.required],
      Email: ['', [Validators.required, Validators.email]],
      Gender: ['', Validators.required],
      DepartmentId: ['', Validators.required],
      PhoneNumber: ['', [Validators.required, Validators.pattern("^(\([0-9]{3}\)|[0-9]{3}-)[0-9]{3}-[0-9]{4}$")]]
    });

    this.loadDepts();

    this.facultyId = this.route.snapshot.paramMap.get('id');
    if (isNaN(+this.facultyId)) {
      console.log('Not a Number!');
      this.router.navigate(['/faculty']);
    }
    else {
      // do api call to retrieve latest faculty information 
      this.dataService.getFaculty(Number(this.facultyId))
        .subscribe(
          data => {
            if (data == null) {
              console.log('faculty not found!');
              this.editFacPanel = false;
              // fail
              // display error message
              this.apiResponse = 'Faculty Not Found!';
              this.responseColor = 'red';
            }
            else {
              this.apiResponse = '';
              this.responseColor = 'green';
              this.editFacPanel = true;

              // console.log(data);
              // popup form data with incoming api data call  
              this.facForm.setValue({
                FirstName: data.firstName,
                LastName: data.lastName,
                Email: data.email,
                Gender: this.convertGenderToFormControl(data.gender),
                DepartmentId: data.departmentId,
                PhoneNumber: data.phoneNumber
              });
            }
          },
          error => {
            console.log(error);
          });
    }
  }

  // ok
  get facFormControl() {
    return this.facForm.controls;
  }

  onSubmit(): void {   
    this.submitted = true;
    if (this.facForm.valid) {
      this.facultyModel.phoneNumber = this.facForm.value["PhoneNumber"];
      this.facultyModel.firstName = this.facForm.value["FirstName"];
      this.facultyModel.lastName = this.facForm.value["LastName"];
      this.facultyModel.email = this.facForm.value["Email"];
      this.facultyModel.departmentId = Number(this.facForm.value["DepartmentId"]);
      this.facultyModel.gender = this.convertGenderToDB(this.facForm.value["Gender"]);
      this.facultyModel.facultyId = Number(this.facultyId);

      this.dataService.editFac(this.facultyModel)
        .subscribe(
          response => {
            if (response.responseCode == 0) {
              // success
              this.apiResponse = response.responseMessage;
              this.responseColor = 'green';
              this.editFacPanel = false;

              // redirect to faculty component
              setTimeout(() => {
                this.router.navigate(['/faculty']);
              }, 3000);
            }
            else {
              // fail
              // display error message
              this.apiResponse = response.responseCode + ' : ' + response.responseMessage;
              this.responseColor = 'red';
              this.editFacPanel = true;
            }
          },
          error => {
            this.apiResponse = error;
            this.responseColor = 'red';
            this.editFacPanel = true;
          }
        );
    }
  }

  resetFac() {  
    this.apiResponse = '';
    this.responseColor = '';
    this.facForm.reset();
    this.submitted = false;

    this.router.navigate(['/faculty']);
  }

  // this will convert gender selectlist value to gender db column
  convertGenderToDB(gender) {
    if (gender == 'Male')
      return 0;
    else if (gender == 'Female')
      return 1;
    else
      return 2;
  }   

  // this will convert gender db column to gender selectlist value
  convertGenderToFormControl(gender) {
    if (gender == 0)
      return 'Male';
    else if (gender == 1)
      return 'Female';
    else
      return 'Other';
  }

  // ok
  loadDepts() {
    this.dataService.getDepartments()
      .subscribe(
        data => {
          this.departments = data;
        },
        error => {
          console.log(error);
        });
  }

  // ok
  /* Gender error handling */
  public handleError = (controlName: string, errorName: string) => {
    return this.facForm.controls[controlName].hasError(errorName);
  }

  // ok
  onPhoneNumberChange(phoneNumber) {
    if (phoneNumber.length == 3) {
      this.facForm.patchValue({
        PhoneNumber: phoneNumber + '-'
      });
    }
    else if (phoneNumber.length == 7) {
      this.facForm.patchValue({
        PhoneNumber: phoneNumber + '-'
      });
    }
    else {
      this.facForm.patchValue({
        PhoneNumber: phoneNumber
      });
    }
  }
}

<div class="container">
    <div class="col-md-10 mx-auto">
        <div class="card" style="background-color: lightgoldenrodyellow;">
            <div class="card-header">
                <h3>
                    <div>
                        #{{facultyId}}) Faculty - Edit
                    </div>
                    <hr />
                    <h4 *ngIf="apiResponse">
                        <span [style.color]="responseColor">
                            {{apiResponse}}
                        </span>
                        <hr />
                    </h4>
                </h3>
            </div>
            <div class="card-body" 
                *ngIf="editFacPanel">
                <form class="form-fac" 
                    [formGroup]="facForm" 
                    (ngSubmit)="onSubmit()">

                    <div class="row">
                        <div class="col-md-6 mx-auto">
                            <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control" formControlName="FirstName">
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(facFormControl.FirstName.touched || submitted) && facFormControl.FirstName.errors?.required">
                                    First Name is required
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" formControlName="LastName">
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(facFormControl.LastName.touched || submitted) && facFormControl.LastName.errors?.required">
                                    Last Name is required
                                </div>
                            </div>
                            <!-- PhoneNumber -->
                            <div class="form-group">
                                <label>Phone </label>
                                <input type="text" 
                                    (input)="onPhoneNumberChange($event.target.value)"
                                    class="form-control" 
                                    formControlName="PhoneNumber">
                                <div *ngIf="(facFormControl.PhoneNumber.touched || submitted) && facFormControl.PhoneNumber.invalid"
                                    class="alert alert-danger mt-2">
                                    <span *ngIf="facFormControl.PhoneNumber.errors.required">Phone Number is required</span>
                                    <span *ngIf="facFormControl.PhoneNumber.errors.pattern">Invalid Phone Number Format</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mx-auto">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="text"
                                    class="form-control" 
                                    formControlName="Email">
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(facFormControl.Email.touched || submitted) && facFormControl.Email.errors?.required">
                                    Email is required
                                </div>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(facFormControl.Email.touched || submitted) && facFormControl.Email.errors?.email">
                                    Invalid Email address
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Gender </label>
                                <select class="form-control" formControlName="Gender">
                                    <option disabled>Select Gender</option>
                                    <option value="">Choose Gender</option>
                                    <option *ngFor="let g of genderCollection">
                                        {{g}}
                                    </option>
                                </select>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(facFormControl.Gender.touched || submitted) && handleError('Gender', 'required')">
                                    Gender is required
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Department </label>
                                <select class="form-control" formControlName="DepartmentId">
                                    <option disabled>Select Department</option>
                                    <option value="">Choose Department</option>
                                    <option value={{d.departmentId}} *ngFor="let d of departments">
                                        {{d.departmentName}}
                                    </option>
                                </select>
                                <div class="alert alert-danger mt-2"
                                    *ngIf="(facFormControl.DepartmentId.touched || submitted) && handleError('DepartmentId', 'required')">
                                    Department is required
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-success">
                                    Edit Faculty
                                </button>
                            </div>
                            <div class="col-sm-2">
                                <button type="button" (click)="resetFac()" class="btn btn-primary">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
             
                </form>
            </div>
        </div>
    </div>
</div>
